#!/bin/bash

function isinteg ()
{
 rm -r "$TRANSDIR/isinteg.$EXT" &> /dev/null
 local EXT=${1: -3}
 if [ "$EXT" == "mp4" ] || [ "$EXT" == "avi" ] || [ "$EXT" == "mkv" ] || [ "$EXT" == "m4v" ] || [ "$EXT" == "M4V" ] || [ "$EXT" == "AVI" ] || [ "$EXT" == "MP4" ] || [ "$EXT" == "M4V" ]; then
 local WRONGEXT="0"
/usr/local/bin/ffmpeg -v error -i "$1" -vframes 10 -y -strict -2 "$TRANSDIR/isinteg.$EXT" < /dev/null
else
 local WRONGEXT="1"
fi
 if [ "$?" == "0" ] && [ "$WRONGEXT" != "1" ]; then
 ISINTEG="1"
 else
 ISINTEG="2"
 fi
rm -r "$TRANSDIR/isinteg.$EXT" &> /dev/null
}
