#!/bin/bash

function movierename()
{
   local FPATH=${1%/*}
   local FFIL=${1##*/}
   local ext=${1: -3}
   local ext=${ext,,}
   if [ -f "$1" ] && [ "$FFIL" != "$1" ]; then
   local WIDTH=`ffprobe -select_streams v -show_streams "$1" 2>/dev/null | grep width | sed -e 's/width=//'`
   local HEIGHT=`ffprobe -select_streams v -show_streams "$1" 2>/dev/null | grep height | sed -e 's/height=//'`
   local VCODEC=`ffprobe -select_streams v -show_streams "$1" 2>/dev/null | grep codec_name | sed -e 's/codec_name=//' | head -n 1`
   local CDTS=`ffprobe -select_streams v -show_streams "$1" 2>/dev/null | grep codec_tag_string | sed -e 's/codec_tag_string=//' | head -n 1`
   local ACODE=`ffprobe -select_streams a -show_streams "$1" 2>/dev/null | grep codec_name | sed -e 's/codec_name=//'`
   local ACODEC1=`ffprobe -select_streams a -show_streams "$1" 2>/dev/null | grep codec_name | sed -e 's/codec_name=//' | head -n 1`
   local ACHANS1=`ffprobe -select_streams a -show_streams "$1" 2>/dev/null | grep channels | sed -e 's/channels=//' | head -n 1`
   local ACODEC2=`ffprobe -select_streams a -show_streams "$1" 2>/dev/null | grep codec_name | sed -e 's/codec_name=//' | tail -n 1`
   local ACHANS2=`ffprobe -select_streams a -show_streams "$1" 2>/dev/null | grep channels | sed -e 's/channels=//' | tail -n 1`
   local ACNT=`wc -l <<< "$ACODE"`
   if [ "$ACNT" -gt "1" ]; then
    local ACODEC=`echo ${ACODEC1^^}"-"$ACHANS1"ch+"${ACODEC2^^}"-"$ACHANS2"ch"`
   else
     local ACODEC=`echo ${ACODEC1^^}"-"$ACHANS1"ch"`
   fi
   local YEAR=`echo "$FFIL" | grep -oE '\([[:alnum:]]*?\)' | sed 's/[()]//g'`
   local MNAME=`echo "$FFIL" | sed -e 's/([^()]*)//g' | sed -e 's/\[[^][]*\]//g' | sed 's/....$//' | sed -e 's/^ *//' -e 's/ *$//'`
   if [ "$WIDTH" == "1920" ]; then
    local VRES="1080p"
   elif [ "$WIDTH" -gt "1279" ] && [ "$WIDTH" -lt "1920" ]; then
    local VRES="720p"
   elif [ "$WIDTH" -gt "719" ] && [ "$WIDTH" -lt "1280" ]; then
    if [ "$HEIGHT" -gt "570" ]; then
     local VRES="576p"
    else
     local VRES="480p"
    fi
   elif [ "$WIDTH" -lt "720" ]; then
    local VRES="SD"
   fi
   if [ "$VCODEC" == "mpeg4" ]; then
    local VCODEC=`echo $CDTS | awk '{print tolower($0)}'`
   fi
   if [ "$HEIGHT" == "" ]; then
    echo "Cannot determine video HEIGHT. Exiting."
    printf "`eval date +%m/%d/%y"-"%H:%M` - 98 Cannot determine VIDEO HEIGHT - $fil \n" >> $LOGF
    exit 1
   fi
   if [ "$WIDTH" == "" ]; then
    echo "Cannot determine video WIDTH. Exiting."
    printf "`eval date +%m/%d/%y"-"%H:%M` - 98 Cannot determine VIDEO WIDTH - $fil \n" >> $LOGF
    exit 1
   fi
   if [ "$VCODEC" == "" ]; then
    echo "Cannot determine video codec. Exiting."
    printf "`eval date +%m/%d/%y"-"%H:%M` - 98 Cannot determine VIDEO CODEC - $fil \n" >> $LOGF
    exit 1
   fi
   if [ "$ACODEC1" == "" ]; then
    echo "Cannot determine audio codec. Exiting."
    printf "`eval date +%m/%d/%y"-"%H:%M` - 98 Cannot determine AUDIO CODEC - $fil \n" >> $LOGF
    exit 1
   fi
   if [ "$ACHANS1" == "" ]; then
    echo "Cannot determine audio channels. Exiting."
    printf "`eval date +%m/%d/%y"-"%H:%M` - 98 Cannot determine AUDIO CHANNELS - $fil \n" >> $LOGF
    exit 1
   fi
# IMDB Lookup
local imdb=`w3m -cols 999 -dump "http://www.omdbapi.com/?t=$MNAME&y=$YEAR"`
local TITLEP=`echo $imdb | awk 'BEGIN {FS="\",\""} {print $1}'`
IFS="\""; read -a TITLEPR <<< "$TITLEP"; IFS="|"
local TITLE=`echo ${TITLEPR[3]} | tr -d '"'`
local TITLE=`echo $TITLE | tr -d "?*/\|<>)[]\""`
local TITLE=`echo $TITLE | sed 's/:/ -/g'`
local TITLE=`echo $TITLE | sed 's/(/ -/g'`
echo $TITLE
if [ "$TITLE" == "False" ]; then
 local imdb=`w3m -cols 999 -dump "http://www.omdbapi.com/?s=$MNAME&y=$YEAR"`
 local TITLEP=`echo $imdb | awk 'BEGIN {FS="\",\""} {print $1}'`
 IFS="\""; read -a TITLEPR <<< "$TITLEP"; IFS="|"
 local TITLE=`echo ${TITLEPR[5]} | tr -d '"'`
 local TITLE=`echo $TITLE | tr -d "?*/\|<>)[]\""`
 local TITLE=`echo $TITLE | sed 's/:/ -/g'`
local TITLE=`echo $TITLE | sed 's/(/ -/g'`
 echo $TITLE
 if [ "$TITLE" == "" ]; then
  local imdb=`w3m -cols 999 -dump "http://www.omdbapi.com/?s=$MNAME"`
  local TITLEP=`echo $imdb | awk 'BEGIN {FS="\",\""} {print $1}'`
  IFS="\""; read -a TITLEPR <<< "$TITLEP"; IFS="|"
  local TITLE=`echo ${TITLEPR[5]} | tr -d '"'`
  local TITLE=`echo $TITLE | tr -d "?*/\|<>)[]\""`
  local TITLE=`echo $TITLE | sed 's/:/ -/g'`
local TITLE=`echo $TITLE | sed 's/(/ -/g'`
  if [ "$TITLE" == "" ]; then
   IMDBOK="0"
  else
   IMDBOK="1"
   local YEARP=`echo $imdb | awk 'BEGIN {FS="\",\""} {print $2}'`
   IFS=":"; read -a YEARPR <<< "$YEARP"; IFS="|"
   local IYEAR=`echo ${YEARPR[1]} | tr -d '"'`
  fi
 else
  IMDBOK="1"
  local YEARP=`echo $imdb | awk 'BEGIN {FS="\",\""} {print $2}'`
  IFS=":"; read -a YEARPR <<< "$YEARP"; IFS="|"
  local IYEAR=`echo ${YEARPR[1]} | tr -d '"'`
 fi
else
 IMDBOK="1"
 local YEARP=`echo $imdb | awk 'BEGIN {FS="\",\""} {print $2}'`
 IFS=":"; read -a YEARPR <<< "$YEARP"; IFS="|"
 local IYEAR=`echo ${YEARPR[1]} | tr -d '"'`
fi
 if [ "$IMDBOK" == "1" ] && [ "$MNAME" != "$TITLE" ]; then
  echo "`eval date +%m/%d/%y"-"%H:%M` - $MNAME ($YEAR) -> $TITLE ($IYEAR)" >> $LOGDIR/imdbrenamed.txt
  MNAME="$TITLE"
 fi
  if [ "$IMDBOK" == "1" ] && [ "$YEAR" != "$IYEAR" ]; then
  echo "`eval date +%m/%d/%y"-"%H:%M` - $MNAME ($YEAR) -> $TITLE ($IYEAR)" >> $LOGDIR/imdbrenamed.txt
  MNAME="$TITLE"
 fi
if [ "$IMDBOK" == "0" ]; then
 echo "`eval date +%m/%d/%y"-"%H:%M` - $MNAME ($YEAR) - $TITLE ($IYEAR)" >> $LOGDIR/imdbfailed.txt
 IYEAR="$YEAR"
fi
   if [ "$YEAR" != "" ]; then
    renamedmoviewp=`echo "$FPATH/$MNAME ($IYEAR) [$VRES][$VCODEC][$ACODEC].$ext" | sed 's/ \+/ /g'`
    renamedmovienp=`echo "$MNAME ($IYEAR) [$VRES][$VCODEC][$ACODEC].$ext" | sed 's/ \+/ /g'`
   else
    echo "$FNAME is missing year, marking file in missing year log "
    printf "$FNAME \n" >> "$LOGDIR/missingyear.txt"
    local YEAR="0000"
    renamedmoviewp=`echo "$FPATH/$MNAME ($IYEAR) [$VRES][$VCODEC][$ACODEC].$ext" | sed 's/ \+/ /g'`
    renamedmovienp=`echo "$MNAME ($IYEAR) [$VRES][$VCODEC][$ACODEC].$ext" | sed 's/ \+/ /g'`
   fi
 else
   echo "File Renamer Problem! $1 file does not exist, or bad path. Exiting."
   printf "`eval date +%m/%d/%y"-"%H:%M` - 79 File Renamer Problem! $1 file does not exist. Exiting. \n" >> $LOGF
   exit 1
fi
}
