#!/bin/bash

source "/opt/galaxymediatools/functions/prechecknl"
LOGF= "/video/Incoming/logs/plexupgrades.log"
LOOPCOUNT=0
WAITHOURS=2  # Hours to wait for plex to be idle before bailing

checkplex() {
PLEXBUSY=`curl -k "https://127.0.0.1:32400/status/sessions?X-Plex-Token=$PLEXTOKEN" | grep 'MediaContainer size="1"' | wc -l`
if [ $PLEXBUSY -ne 0 ]; then
 if [ $LOOPCOUNT -eq 0 ]; then
  log "WARN" "Plex server is busy, postponing reboot..."
 fi
sleep 600
fi
((LOOPCOUNT++))
echo $PLEXBUSY
}

starttimer
HOURLOOP=$((WAITHOURS * 6))
until [ $LOOPCOUNT -eq $HOURLOOP ]; do
PCHECK=$(checkplex)
if [ $PCHECK -eq 0 ]; then
 ELAPSED=$((elapsed))
 log "INFO" "Plex is idle and needs reboot, rebooting. Elapsed: $ELAPSED"
 if [ $LOOPOUNT -gt 1 ]; then

 starttimer2
 log "INFO" "Starting Plexupdate..."
 /opt/plexupdate/plexupdate.sh -d --notify-success --config /etc/plexupdate.conf -u &>> $LOGF
 ELAPSED2=$(elapsed2)
 log "INFO" "Plexupdate complete. Elapsed: $ELAPSED2"

 fi
 LOOPCOUNT=99
 /sbin/reboot
 exit 0
fi
done
ELAPSED=$((elapsed))
NEWST=$(HOURLOOP-1)
if [ $LOOPCOUNT -gt $NEWST ]; then
log "WARN" "Plex still busy after $WAITHOURS Hours. Skipping reboot. Elapsed: $ELAPSED"
fi


