#!/bin/bash

source "/opt/galaxymediatools/functions/prechecknl"

if mkdir "/var/lock/gtrans.lock"; then
trap control_c SIGINT
trap appexit EXIT
else
echo -e "${rred}Process locked. Lock file detected. Can only run 1 transcode script at a time. Exiting.${nocolor}"
exit 1
fi


