#!/bin/bash
control_c()
{
  echo -en "\n*** Ouch! Exiting ***\n"
  rm -rf /var/lock/gtrans.lock &> /dev/null
  exit $?
}

appexit()
{
  rm -rf /var/lock/gtrans.lock &> /dev/null
  exit $?
}

function gettime {
TTIME=$(($2 - $1))
MIN=$((TTIME / 60))
HRS=$((MIN / 60))
MINR=$((MIN % 60))
if [ "$HRS" != "0" ]; then
echo -e "$HRS Hours and $MINR Minutes"
else
echo -e "$MIN Minutes"
fi
}

LOGDT="eval date '+%y/%m/%d %H:%M:%S'"

log () {
echo "`$LOGDT` - $1 :: $2" >> $LOGF
}


yellow='\e[1;33m'
dyellow='\e[0;33m'
red='\e[0;31m'
cyan='\e[1;36m'
dcyan='\e[0;36m'
white='\e[1;37m'
green='\e[1;32m'
dgreen='\e[0;32m'
magenta='\e[1;35m'
blue='\e[1;34m'
pink='\e[1;31m'
rred='\e[1;41m\e[1;37m'
nocolor='\e[0m'
bold='\e[1;01m'
blink='\e[1;05m'
reverse='\e[1;07m'

servercolor=${magenta} # server name color
cmd1color=${dcyan} # command 1 color
cmd2color=${pink} # cmmand 2 color
soutcolor=${dyellow} # Server output color
errorcolor=${rred} # error color
syscolor=${blue} # System color

THISSERVER=`hostname`
APPDIR="/opt/galaxymediatools"
STIME=$(date +%s)
CTS=`eval date +%Y%m%d`
if [ ! -f "/etc/galaxymediatools.conf" ]; then
 echo -e "No config file found. Exiting."
 exit 1
else
 source /etc/galaxymediatools.conf
fi
if [ "$THISSERVER" == "$T1NAME" ]; then
POAK=$T1KEY
elif [ "$THISSERVER" == "$T2NAME" ]; then
POAK=$T2KEY
fi
T1IP=`sed -e 's#.*@\(\)#\1#' <<< "$T1INFO"`
T2IP=`sed -e 's#.*@\(\)#\1#' <<< "$T2INFO"`
if [ "$LOGDIR" == "" ] || [ "$TVDIR" == "" ] || [ "$TRANSDIR" == "" ] || [ "$POUK" == "" ] || [ "$PLEXINFO" == "" ] || [ "$PLEXCAT" == "" ]; then
echo -e "${rred}No config information found in config file. Exiting.${nocolor}"
exit 1
fi
