#!/bin/bash

if [ "$2" == "-w" ]; then
sleep 10
fi

if [ -d /var/lock/gtrans.lock ]; then echo 1; exit 1; fi
DVR=`sudo ps uxa | grep PlexComskip.py | wc -l`
if [ $DVR -gt 1 ]; then echo 1; exit 1; fi
SSCAN=`sudo ps uxa | grep securityscan | wc -l`
if [ $SSCAN -gt 1 ]; then echo 1; exit 1; fi
MAINT=`sudo ps uxa | grep galaxy_maintenance | wc -l`
if [ $MAINT -gt 1 ]; then echo 1; exit 1; fi
FFMPEG=`sudo ps uxa | grep ffmpeg | wc -l`
if [ $FFMPEG -gt 1 ]; then echo 1; exit 1; fi
echo 0
if [ "$1" == "-s" ]; then
pm-suspend &
fi
exit 0
