#!/bin/bash

function whichserver ()
{ 
fping -c1 -t300 $T1IP 2>/dev/null 1>/dev/null
if [ "$?" == "0" ]; then
 if (ssh $T1INFO '[ -d /var/lock/gtrans.lock ]'); then
  local T1STAT="2"
 else
  local T1STAT="1"
 fi
else
 local T1STAT="0"
fi
fping -c1 -t300 $T2IP 2>/dev/null 1>/dev/null
if [ "$?" == "0" ]; then
 if (ssh $T2INFO '[ -d /var/lock/gtrans.lock ]'); then
  local T2STAT="2"
 else
  local T2STAT="1"
fi
 else
  local T2STAT="0"
fi
if [ "$T2STAT" == "0" ]; then
 eval /opt/galaxymediatools/remotewake "$T2NAME"
 WHICHSERVER="$T2NAME"
 sleep 10
elif [ "$T2STAT" == "1" ]; then
 WHICHSERVER="$T2NAME"
elif [ "$T2STAT" == "2" ] && [ "$T1STAT" == "0" ]; then
 eval /opt/galaxymediatools/remotewake "$T1NAME"
 sleep 10
 WHICHSERVER="$T1NAME"
elif [ "$T2STAT" == "2" ] && [ "$T1STAT" == "1" ]; then
 WHICHSERVER="$T1NAME"
elif [ "$T2STAT" == "2" ] && [ "$T1STAT" == "2" ]; then
 WHICHSERVER="NONE"
fi
}
