#!/bin/bash

LOGF="/video/Incoming/logs/backupmaster.log"

source "/opt/galaxymediatools/functions/prechecknl"

if /bin/mountpoint -q /video
then

log "INFO" "---> Backup script starting"

RUNCHECK1=`ps uxa | grep "backuplauncher" | wc -l`

if [[ $RUNCHECK1 < 3 ]]; then
   /usr/bin/screen -dm bash -c "/opt/galaxymediatools/backupscripts/backuplauncher" &>> $LOGF
  else
   log "WARN" "Backup already running.  Not executing another session."
   exit 1
  fi

else
log "ERROR" "Video NFS Share NOT MOUNTED!! Exiting."
fi
