#!/bin/bash

LOGF="/export/incoming/logs/backupmaster.log"

source "/opt/galaxymediatools/functions/prechecknl"


if [ "$1" == "--help" ] || [ "$1" == "-h" ]; then
echo "Galaxy Backup Startup script"
echo " "
exit 0
fi

if [ "$1" != "" ] && [ "$1" != "-h" ] && [ "$1" != "--help" ] && [ "$1" != "-ns" ]; then
echo "backupstart: Invalid option specified.  See backupstart --help"
exit 1
fi

log "INFO" "---> Backup script starting"

RUNCHECK1=`ps uxa | grep "backuplauncher" | wc -l`

if [ $RUNCHECK1 -lt 2 ]; then
   /usr/bin/screen -S "backups" -t "backups" -dm bash -c "/opt/galaxymediatools/backupscripts/backuplauncher $1" &>> $LOGF
  else
   log "WARN" "Backup already running.  Not executing another session."
   exit 1
fi

