#!/bin/bash

LOCKDIR=/run/lock/checknet
APPDIR=/opt/galaxymediatools
LOGF="/video/Incoming/logs/connection.log"

source="/opt/galaxymediatools/functions/prechcknl"

function cleanup {
    if rmdir $LOCKDIR; then
     exit
    else
        echo "Failed to remove lock directory '$LOCKDIR'"
        exit 1
    fi
}

if mkdir $LOCKDIR; then
 trap "cleanup" EXIT
 STIME=$(date +%s)
 if [ ! -f "$LOGF" ]; then
 /usr/bin/touch "$LOGF"
 fi
 
 fping -c1 -t3000 www.google.com 2>/dev/null 1>/dev/null
 if [ "$?" == "0" ]; then
  exit
 else
  RES=0
  PCOUNT=0
  starttimer
  sleep 7
 while [ $RES -eq 0 ]; do
  ((PCOUNT++))
  fping -c1 -t3000 www.google.com 2>/dev/null 1>/dev/null
  if [ $? -eq 0 ]; then
   RES=1
   else
   if [ $PCOUNT -eq 1 ]; then
   log "WARN" "Network Outage Detected."
   fi
   sleep 7
  fi
 done
  if [ $PCOUNT -gt 3 ]; then
  ELAPSED=$(elapsed)
  log "WARN" "Network Outage Returned. Elapsed: $ELAPSED"
  pushover "connection" "Network Outage Loagged: $ELAPSED"
  fi
 fi 
else
 echo "Could not create lock directory '$LOCKDIR'"
 exit 1
fi
