#!/bin/bash

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
        echo " "
        echo "Galaxy Media Tools - Transcode Server Status"
        echo " "
        echo "-h or --help : Help"
        echo "-u : Upgrade from git only"
        echo " "
        exit 0
fi

if [ "$1" == "" ]; then
	echo "Argument missing. Specify which transcode server to start-up"
	exit 1
fi

source /opt/galaxymediatools/precheck

if [ "$1" == "$T1NAME" ]; then
 fping -c1 -t300 $T1IP 2>/dev/null 1>/dev/null
  if [ "$?" == "0" ]; then
   echo "$T1NAME server is UP."
   ssh $T1INFO "sudo top -n 1 | head -4" 
 else
  echo "$T1NAME server is DOWN."
  exit 0
 fi
fi

