#!/bin/bash

source /opt/galaxymediatools/functions/prechecknl

echo "------"
printf "${white}White - This is white text.\n"
printf "${cyan}cyan - This is cyan text.\n"
printf "${yellow}yellow - This is yellow text.\n"
printf "${green}green - This is green text.\n"
printf "${red}red - This is red text.\n"
printf "${blue}blue - This is blue text.\n"
printf "${magenta}Magenta - This is magenta text.\n"
printf "${nocolor}\n"
printf "${bold}Bold - This is bold text.${nocolor}\n"
printf "${blink}Blink - This is blinking text.${nocolor}\n"
printf "${reverse}Reverse - This is reverse text.${nocolor}\n"
printf "${rred}Reverse Red - This is Red Reverse text.${nocolor}\n"
echo "------"
