#!/bin/bash

source "/opt/galaxymediatools/functions/prechecknl"

LOGF="/video/Incoming/logs/comcutter.log"
 FNO=${1##*/} # filename only with extentions
 EXT=${1: -3} # extention only
 FPNE="${1%.*}"  # filename with path no extention
 FNPNE="${FPNE##*/}"  # no path no extention
 DIR=$(dirname "${1}") # path only

echo "FNO: $FNO"
echo "EXT: $EXT"
echo "FPNE: $FPNE"
echo "FNPNE: $FNPNE"
echo "DIR: $DIR"

#echo "Staring automatic commercial editor script" >> $LOGF

#echo "Running on file: $fng" >> $LOGF

#echo "Running comskip commercial locator..." >> $LOGF
#/opt/Comskip/comskip "$1" --ini=/opt/Comskip/comskip.ini --output=$LOGDIR/comskip $LOGDIR/comskip
#echo "Comskip processing complete." >> $LOGF

# check here for exit code
# add execute times

#echo "Running mencoder to remove commercials..." >> $LOGF
#mencoder "$1" -edl "$LOGDIR/comskip/$fne.edl" -oac copy -ovc copy -of mpeg -o "/TRANSCODE/test.mpg"
#echo "Mencoder processing complete." >> $LOGF

#mv /TRANSCODE/test.mpg $LOGDIR

#echo "Completed automatic commercial editor script" >> $LOGF

