#!/bin/bash

source "/etc/galaxymediatools.conf"

read -r -p "Would you like to generate new ssh auth keys? [y/N] " response
response=${response,,}    # tolower
if [[ $response =~ ^(yes|y)$ ]]; then
ssh-keygen
fi
echo "Copying ssh keys to transcode servers..."
ssh-copy-id $T1INFO
ssh-copy-is $T2INFO
