#!/bin/bash

LOGF="/video/Incoming/logs/dvrpostprocess.log"

source "/opt/galaxymediatools/functions/prechecknl"

SLEPT=0
starttimer
FNO=${1##*/}
log "INFO" "---> Starting Recorded TV post process"
log "INFO" "Running on recording: $FNO"
log "INFO" "Checking transcode server state..."

echo -e "Conecting to remote Server ${servercolor}$T1NAME${cmd1color}..."
 fping -c1 -t300 $T1IP 2>/dev/null 1>/dev/null
  if [ "$?" != "0" ]; then
   WASSLEEPING1=1
   echo -e "${cmd2color}Waking transcode server ${servercolor}$T1NAME"
  printf "${soutcolor}"
   wakeonlan $T1MAC
   wakeonlan $T1MAC
   printf "${nocolor}"
   SERVERUP=0
until [ $SERVERUP -eq 1 ]; do
  fping -c1 -t300 $T1IP 2>/dev/null 1>/dev/null
  if [ $? -eq 0 ]; then
  sleep 1
  SERVERUP=1
  fi
done
   echo -e "${cmd1color}Transcode server ${servercolor}$T1NAME ${cmd1color}started"
  fi

starttimer2
log "INFO" "Executing remote PlexComskip script"

ssh $T1INFO "sudo /opt/galaxymediatools/dvrprocess/PlexComskip.py \"$1\"" &

wait

ELAPSED2=$(elapsed2)
log "INFO" "PlexComskip script complete. Elapsed: $ELAPSED2"

sleep 10
ssh $T1INFO "sudo /opt/galaxymediatools/functions/transidlecheck -s" &

ELAPSED=$(elapsed)
log "INFO" "<--- Completed Recorded TV post process. Elapsed: $ELAPSED"

#curl http://[PMS_IP_ADDRESS]:32400/library/sections/5/refresh?X-Plex-Token=$PLEXTOKEN
