#!/bin/bash

LOGF="/video/Incoming/logs/dvrpostprocess.log"

source "/opt/galaxymediatools/functions/prechecknl"

SLEPT=0
starttimer
FNO=${1##*/}
log "INFO" "---> Starting Recorded TV post process"
log "INFO" "Running on recording: $FNO"
log "INFO" "Checking transcode server state..."
fping -c1 -t300 $T1IP 2>/dev/null 1>/dev/null
if [ $? -ne 0 ]; then
  SLEPT=1
  log "INFO" "Attempting to wake server $T1NAME..."
  wakeonlan $T1MAC 2>/dev/null 1>/dev/null
  wakeonlan $T1MAC 2>/dev/null 1>/dev/null
  sleep 60
  fping -c1 -t300 $T1IP 2>/dev/null 1>/dev/null
if [ $? -ne 0 ]; then
  log "ERROR" "$T1NAME failed wake and server is not responding."
  exit 1
fi
fi

starttimer2
log "INFO" "Executing remote PlexComskip script"

ssh $T1INFO "sudo /opt/galaxymediatools/dvrprocess/PlexComskip.py \"$1\"" &

wait

ELAPSED2=$(elapsed2)
log "INFO" "PlexComskip script complete. Elapsed: $ELAPSED2"

if [ $SLEPT -eq 1 ]; then
log "INFO" "$T1NAME was originally sleeping, putting back to sleep"
ssh $T1INFO "sudo pm-suspend" & 
fi

ELAPSED=$(elapsed)
log "INFO" "<--- Completed Recorded TV post process. Elapsed: $ELAPSED"

#curl http://[PMS_IP_ADDRESS]:32400/library/sections/5/refresh?X-Plex-Token=$PLEXTOKEN
