#!/bin/bash

LOGF="/video/Incoming/logs/expiredtv.log"

source "/opt/galaxymediatools/functions/prechecknl"

TV1="/video/TV Series/Vice News Tonight/Season 01"
TV2="/video/Recorded TV/Local 4 News Today at 6AM (2013)/Season 2017"

starttimer
log "INFO" "---> Starting TV episode experation check script"

log "INFO" "Checking for expired episodes..."

#find "$TV1" -type f -printf "%-.22T+ %M %n %-8u %-8g %8s %Tx %.8TX %p\n" | sort | cut -f 2- -d ' ' 

EPS1=`find "$TV1" -mtime +14 | wc -l`
EPS2=`find "$TV2" -mtime +1 | wc -l`
EPS=$((EPS1+EPS2))

log "INFO" "Found $EPS expired TV episodes."

log "INFO" "Removing $EPS expired TV episodes."
find "$TV1" -mtime +14 -exec rm -rf {} \; &>> $LOGF
find "$TV2" -mtime +1 -exec rm -rf {} \; &>> $LOGF
log "INFO" "Removed $EPS expired TV episodes."
log "INFO" "Updating plex libraries"

/usr/bin/curl "http://172.25.1.26:32400/library/sections/$PLEXCAT/refresh?X-Plex-Token=$PLEXTOKEN"
sleep 10
/usr/bin/curl "http://172.25.1.26:32400/library/sections/$PLEXRCAT/refresh?X-Plex-Token=$PLEXTOKEN"

ELAPSED=$(elapsed)
pushover "transcoder" "TV episode experation complete. $EPS Episodes removed. Elapsed: $ELAPSED" &> /dev/null

log "INFO" "<--- Complete TV episode experation check. Elapsed: $ELAPSED"

exit 0
