#!/bin/bash

LOGF="/video/Incoming/logs/securityscan-nasscan.log"

source "/opt/galaxymediatools/functions/prechecknl"

starttimer

log "INFO" "---> Security file scan starting."

if mountpoint -q /video
then
 echo " "
else
 log "ERROR" "/video not mounted. Exiting."
 pushover "security" "NASscan Error: /video not mounted, cannot continue."
 exit 1
fi

THREAT="No threats found."

scanfiles() {
starttimer2
log "INFO" "*Scanning $1"
/opt/sophos-av/bin/savscan -ss -archive -suspicious -move=/video/Other/infected $1 >> $LOGF
  if [ $? -eq 1 ]; then
    THREAT="Skipped files or interrupted"
  else
    if [ $? -eq 2 ]; then
     pushover "security" "Sophos Execution error on NAS file scan. Check $LOGF" 
    THREAT="Execution Error"
   else
    if [ $? -eq 3 ]; then
      THREAT="THREAT FOUND!!"
      pushover "security" -T "Security Threat Found on NAS file scan. Check $LOGF"
    fi
  fi
fi
ELAPSED2=$(elapsed2)
log "INFO" "Scan of $1 complete. Result: $THREAT. Elapsed: $ELAPSED2"
}

#V1=`df -h | grep "/video"`
#IFS=' ' read -r -a VDINFO <<< $V1
#VDPERC=${VDINFO[4]}
#VDFREE=${VDINFO[3]}
#VDUSED=${VDPERC::-1}
#if [ $VDUSED -gt 98 ];then
# log "WARN" "Low space on NAS!! $VDFREE Free, $VDPERC Used."
# pushover "security" "Low space on NAS!! $VDFREE Free, $VDPERC Used."
#fi

starttimer3
log "INFO" "Starting Sophos definition update..."
/opt/sophos-av/bin/savupdate &>> $LOGF
ELAPSED3=$(elapsed3)
    if [ $? -ne 0 ]; then
      pushover "security" "Sophos definition update error on NASscan. Check logs."
      log "ERROR" "Sophos definition update error. Elapsed: $ELAPSED3"
    SUEXIT="Update Error!!"
    else
     log "INFO" "Sophos definition update completed successfully.i Elapsed: $ELAPSED3"
    SUEXIT="Success"
    fi


scanfiles /video/Incoming
scanfiles /pictures
scanfiles /files

ELAPSED=$(elapsed)
#pushover "security" -T "Security file scan complete. $THREAT Elapsed: $ELAPSED" &> /dev/null

log "INFO" "<--- Security file scan completed. Elapsed: $ELAPSED"
exit 0
