#!/bin/bash

if mount|grep "/mnt/storage" > /dev/null; then
echo "File cleanup running..."
MDIR="/mnt/storage/video/Movies/"

rm -fr /mnt/storage/video/Incoming/process/tv/*
rm -fr /mnt/storage/video/Incoming/process/movies/*

#find $MDIR -mindepth 2 -type f -print -exec mv {} . \;
find $MDIR -type d -empty -exec rmdir {} \;
rm $MDIR*.nfo >> /dev/null 2>&1
rm $MDIR*.txt >> /dev/null 2>&1
rm $MDIR*.jpg >> /dev/null 2>&1
rm $MDIR*.gif >> /dev/null 2>&1
rm $MDIR*.idx >> /dev/null 2>&1
rm $MDIR*.sub >> /dev/null 2>&1
rm $MDIR*.srt >> /dev/null 2>&1
rm $MDIR*.exe >> /dev/null 2>&1
rm $MDIR*.me >> /dev/null 2>&1
rm $MDIR*. >> /dev/null 2>&1
rm $MDIR*sample* >> /dev/null 2>&1
rm $MDIR*unknown.ignore >> /dev/null 2>&1
echo "File cleanup Complete."
else
echo "/mnt/storage NOT MOUNTED!! Exiting."
exit 1
fi
