#!/bin/bash

if mount|grep "/mnt/storage" > /dev/null; then
echo "File permission reset running..."

chmod ugo+rw /mnt/storage/music/process -R
chmod ugo+rw /mnt/storage/video/Incoming -R
if [ "$1" != "-l" ]; then
chmod ugo+rw "/mnt/storage/video/Recorded TV" -R
chmod ugo+rw "/mnt/storage/video/Movies" -R
chmod ugo+rw "/mnt/storage/video/TV Series" -R
fi

else
echo "/mnt/storage NOT MOUNTED!! Exiting."
exit 1
fi

echo "File permission reset Complete."
exit 0
