#!/bin/bash

source "/opt/galaxymediatools/functions/prechecknl"

LOGF="/video/Incoming/logs/maintenance.log"

if mountpoint -q /video
then
RUNCHECK1=`ps uxa | grep "galaxy_maintenance" | wc -l`

 STTIME=`date +%m/%d/%y" "%l:%M%P`
 log "INFO" "---> Starting Galaxy maintenance script"

 if [[ $RUNCHECK1 < 4 ]]; then 
  PTIME=$(date +%s)  
  echo "`eval date +%m/%d/%y"-"%H:%M` Starting file cleanup..." >> $LOGF
  /opt/galaxymediatools/filecleanup >> $LOGF
  OTIME=$(date +%s)
  RTIME=$(gettime "$PTIME" "$OTIME")
  echo "`eval date +%m/%d/%y"-"%H:%M` Completed file cleanup. Elapsed: $RTIME" >> $LOGF
 
  PTIME=$(date +%s)
  echo "`eval date +%m/%d/%y"-"%H:%M` Starting file permission reset..." >> $LOGF
  /opt/galaxymediatools/filepermissions >> $LOGF
  OTIME=$(date +%s)
  RTIME=$(gettime "$PTIME" "$OTIME")
  echo "`eval date +%m/%d/%y"-"%H:%M` Completed file permission reset. Elapsed: $RTIME" >> $LOGF

  PTIME=$(date +%s)
  echo "`eval date +%m/%d/%y"-"%H:%M` Starting expired episode check..." >> $LOGF
  /opt/galaxymediatools/expiredtv >> $LOGF
  OTIME=$(date +%s)
  RTIME=$(gettime "$PTIME" "$OTIME")
  echo "`eval date +%m/%d/%y"-"%H:%M` Completed expired episode check. Elapsed: $RTIME" >> $LOGF

  PTIME=$(date +%s)
  echo "`eval date +%m/%d/%y"-"%H:%M` Starting file security scan..." >> $LOGF
  /opt/galaxymediatools/filescan >> $LOGF
  OTIME=$(date +%s)
  RTIME=$(gettime "$PTIME" "$OTIME")
  echo "`eval date +%m/%d/%y"-"%H:%M` Completed file security scan. Elapsed: $RTIME" >> $LOGF

  PTIME=$(date +%s)
  echo "`eval date +%m/%d/%y"-"%H:%M` Executing Mass Movie Renamer..." >> $LOGF
  /opt/galaxymediatools/massmovierenamer -i &> /dev/null
  OTIME=$(date +%s)
  RTIME=$(gettime "$PTIME" "$OTIME")
  echo "`eval date +%m/%d/%y"-"%H:%M` Mass Movie renamer complete. Elapsed: $RTIME" >> $LOGF

  PTIME=$(date +%s)
  echo "`eval date +%m/%d/%y"-"%H:%M` Executing Mass TV Transcoder..." >> $LOGF
  /opt/galaxymediatools/masstvtrans &> /dev/null
  OTIME=$(date +%s)
  RTIME=$(gettime "$PTIME" "$OTIME")
  echo "`eval date +%m/%d/%y"-"%H:%M` Mass TV Transcoder complete. Elapsed: $RTIME" >> $LOGF

  PTIME=$(date +%s)
  echo "`eval date +%m/%d/%y"-"%H:%M` Executing master backup script..." >> $LOGF
  /opt/galaxymediatools/backupstart &> /dev/null
  OTIME=$(date +%s)
  RTIME=$(gettime "$PTIME" "$OTIME")
  echo "`eval date +%m/%d/%y"-"%H:%M` Master backup script complete. Elapsed: $RTIME *This process branchs off" >> $LOGF

  else
   echo "`eval date +%m/%d/%y"-"%H:%M` Maintenance script already running.  Not executing another session." >> $LOGF
   exit 1
 fi

TTIME=$(date +%s)
   ETIME=$(gettime "$STIME" "$TTIME")
 ET=`date +%m/%d/%y" "%l:%M%P`

echo "`eval date +%m/%d/%y"-"%H:%M` <--- Completed galaxy maintenance script. Elapsed: $ETIME --------" >> $LOGF
 
else
 echo "`eval date +%m/%d/%y"-"%H:%M` Video NFS Share NOT MOUNTED!! Exiting." >> $LOGF
 exit 1
fi
