#!/bin/bash
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/opt/galaxymediatools"
export PATH=$PATH

LOGF="/video/Incoming/logs/maintenance.log"

source "/opt/galaxymediatools/functions/prechecknl"

starttimer
if mountpoint -q /video
then
RUNCHECK1=`ps uxa | grep "galaxy_maintenance" | wc -l`

 log "INFO" "---> Starting Galaxy maintenance script"

 if [[ $RUNCHECK1 < 4 ]]; then 
  starttimer2  
  log "INFO" "Starting file cleanup..."
  /opt/galaxymediatools/filecleanup >> $LOGF
  ELAPSED2=$(elapsed2)
  log "INFO" "Completed file cleanup. Elapsed: $ELAPSED2"
 
  starttimer2
  log "INFO" "Starting file permission reset..."
  /opt/galaxymediatools/filepermissions >> $LOGF
  ELAPSED2=$(elapsed2)
  log "INFO" "Completed file permission reset. Elapsed: $ELAPSED2"

  starttimer2
  log "INFO" "Starting expired episode check..."
  /opt/galaxymediatools/expiredtv >> $LOGF
  ELAPSED2=$(elapsed2)
  log "INFO" "Completed expired episode check. Elapsed: $ELAPSED2"

  starttimer2
  log "INFO" "Starting file security scan..."
  /opt/galaxymediatools/filescan >> $LOGF
  ELAPSED2=$(elapsed2)
  log "INFO" "Completed file security scan. Elapsed: $ELAPSED2"

  starttimer2
  log "INFO" "Executing Mass Movie Renamer..."
  /opt/galaxymediatools/massmovierenamer -i &> /dev/null
  ELAPSED2=$(elapsed2)
  log "INFO" "Mass Movie renamer complete. Elapsed: $ELAPSED2"

  starttimer2
  log "INFO" "Executing Mass TV Transcoder..."
  /opt/galaxymediatools/masstvtrans &> /dev/null
  ELAPSED2=$(elapsed2)
  log "INFO" "Mass TV Transcoder complete. Elapsed: $ELAPSED2"

  starttimer2
  log "INFO" "Checking Servers for freespace..."
  /opt/galaxymediatools/filespacefree -q -n >> $LOGF
  ELAPSED2=$(elapsed2)
  log "INFO" "Freespace check complete. Elapsed: $ELAPSED2"

  starttimer2
  log "INFO" "Executing master backup script..."
  /opt/galaxymediatools/backupstart &> /dev/null
  ELAPSED2=$(elapsed2)
  log "INFO" "Master backup script complete. Elapsed: $ELAPSED2 *This process branchs off"

  else
   log "WARN" "Maintenance script already running.  Not executing another session."
   exit 1
 fi

ELAPSED=$(elapsed)

log "INFO" "<--- Completed galaxy maintenance script. Elapsed: $ELAPSED"
 
else
 log "ERROR" "Video NFS Share NOT MOUNTED!! Exiting."
 exit 1
fi
