#!/bin/bash
APPDIR="/opt/galaxymediatools"
if [ ! -f "/etc/galaxymediatools.conf" ]; then
 echo -e "No config file found. Exiting."
 exit 1
else
 source /etc/galaxymediatools.conf
fi
if [ "$LOGDIR" == "" ] || [ "$TVDIR" == "" ] || [ "$TRANSDIR" == "" ] || [ "$POUK" == "" ] || [ "$PLEXINFO" == "" ] || [ "$PLEXCAT" == "" ]; then
echo -e "No config information found in config file. Exiting."
exit 1
fi
cd "$APPDIR"
git pull origin $GITREPO
cp /opt/galaxymediatools/bashrc /home/ip/.bashrc
cp /opt/galaxymediatools/bashrc.root /root/.bashrc
exit 0

