#!/bin/bash
UPG=$(git pull origin master | grep "Already")
if [ "$UPG" != "Already up-to-date." ]; then
  echo "upgrading"
  git pull origin master
  bash $APPDIR/$APPNAME
  exit 0
else
echo "no upgrade needed"
fi

