#!/bin/bash
THISSERVER=`hostname`
APPDIR="/opt/galaxymediatools"
if [ ! -f "/etc/galaxymediatools.conf" ]; then
 echo -e "No config file found. Exiting."
 exit 1
else
 source /etc/galaxymediatools.conf
fi
T1IP=`sed -e 's#.*@\(\)#\1#' <<< "$T1INFO"`
T2IP=`sed -e 's#.*@\(\)#\1#' <<< "$T2INFO"`
if [ "$LOGDIR" == "" ] || [ "$TVDIR" == "" ] || [ "$TRANSDIR" == "" ] || [ "$POUK" == "" ] || [ "$PLEXINFO" == "" ] || [ "$PLEXCAT" == "" ]; then
echo -e "No config information found in config file. Exiting."
exit 1
fi

echo "Pushing files to git repository..."
git add *
git commit -m "working"
git push origin $GITREPO
echo "Conecting to remote Server $T1INFO..."
 fping -c1 -t300 $T1IP 2>/dev/null 1>/dev/null
  if [ "$?" != "0" ]; then
   WASSLEEPING1="1"
   echo "Waking transcode server $T1NAME"
   wakeonlan $T1MAC
   sleep 10
   echo -e "Transcode server $T1NAME started"
  fi
 ssh $T1INFO "sudo $APPDIR/gitpull"
 if [ "$WASSLEEPING1" == "1" ]; then
  echo "Transcoder server $T1NAME was sleeping, putting back to sleep."
  ssh $T1INFO 'sudo pm-suspend' &
 fi

echo "Connecting to remote Server $T2INFO..."
 fping -c1 -t300 $T2IP 2>/dev/null 1>/dev/null
  if [ "$?" != "0" ]; then
  WASSLEEPING2="1"
   echo "Waking transcode server $T2NAME"
   wakeonlan $T2MAC
   sleep 10
   echo -e "Transcode server $T2NAME started"
  fi
 ssh $T2INFO "sudo $APPDIR/gitpull"
 if [ "$WASSLEEPING2" == "1" ]; then
  echo "Transcoder server $T2NAME was sleeping, putting back to sleep."
  ssh $T2INFO 'sudo pm-suspend' &
 fi


