#!/bin/bash

source "/opt/galaxymediatools/functions/prechecknl"
WASSLEEPING1=0
cp /root/.ssh/id_rsa /root/.ssh/github_id_rsa -f
echo -e "${cmd1color}Pushing files to git repository..."
printf "${syscolor}"
git add *
git commit -m "working"
git push origin $GITREPO
printf "${nocolor}"
if [ "$HOSTNAME" != "$T1NAME" ]; then
echo -e "Conecting to remote Server ${servercolor}$T1NAME${cmd1color}..."
 fping -c1 -t300 $T1IP 2>/dev/null 1>/dev/null
  if [ "$?" != "0" ]; then
   WASSLEEPING1=1
   echo -e "${cmd2color}Waking transcode server ${servercolor}$T1NAME"
  printf "${soutcolor}"
   wakeonlan $T1MAC
   wakeonlan $T1MAC
   printf "${nocolor}"
   SERVERUP=0
until [ $SERVERUP -eq 1 ]; do
  fping -c1 -t300 $T1IP 2>/dev/null 1>/dev/null
  if [ $? -eq 0 ]; then
  sleep 1
  SERVERUP=1
  fi
done   
   echo -e "${cmd1color}Transcode server ${servercolor}$T1NAME ${cmd1color}started"
  fi
 printf "${soutcolor}"
 ssh $T1INFO "sudo $APPDIR/gitpull"
 printf "${nocolor}"
 if [ $WASSLEEPING1 -eq 1 ]; then
  echo -e "${cmd2color}Transcoder server ${servercolor}$T1NAME ${cmd2color}was sleeping, putting back to sleep.${nocolor}"
  ssh $T1INFO 'sudo pm-suspend' &
 fi
fi

#echo -e "${cmd1color}Connecting to remote Server ${servercolor}$T2NAME${cmd1color}..."
# fping -c1 -t300 $T2IP 2>/dev/null 1>/dev/null
#  if [ "$?" != "0" ]; then
#  WASSLEEPING2="1"
#   echo -e "${cmd2color}Waking transcode server ${servercolor}$T2NAME"
# printf "${soutcolor}"
#   wakeonlan $T2MAC
#   wakeonlan $T2MAC
# printf "${nocolor}"
#   sleep 10
#   echo -e "${cmd1color}Transcode server ${servercolor}$T2NAME ${cmd1color}started"
#  fi
# printf "${soutcolor}"
# ssh $T2INFO "sudo $APPDIR/gitpull"
# printf "${nocolor}"
# if [ "$WASSLEEPING2" == "1" ]; then
#  echo -e "${cmd2color}Transcoder server ${servercolor}$T2NAME ${cmd2color}was sleeping, putting back to sleep.${nocolor}"
#  ssh $T2INFO 'sudo pm-suspend' &
# fi

if [ "$THISSERVER" != "$MSNAME" ]; then
echo -e "Connecting to remote Server ${servercolor}$MSNAME${cmd1color}..."
 printf "${soutcolor}"
 ssh $MSINFO "sudo $APPDIR/gitpull"
 printf "${nocolor}"
fi

if [ "$THISSERVER" != "$DSNAME" ]; then
echo -e "Connecting to remote Server ${servercolor}$DSNAME${cmd1color}..."
 printf "${soutcolor}"
 ssh $DSINFO "sudo $APPDIR/gitpull"
 printf "${nocolor}"
fi

if [ "$THISSERVER" != "$PLEXNAME" ]; then
echo -e "Connecting to remote Server ${servercolor}$PLEXNAME${cmd1color}..."
 printf "${soutcolor}"
 ssh $PLEXINFO "sudo $APPDIR/gitpull"
 printf "${nocolor}"
fi
echo -e "${nocolor}"
cp /opt/galaxymediatools/conf/bashrc /home/ip/.bashrc
cp /opt/galaxymediatools/conf/bashrc.root /root/.bashrc
cp /opt/galaxymediatools/conf/rc.local /etc/rc.local
