#!/bin/bash
THISSERVER=`hostname`
APPDIR="/opt/galaxymediatools"
if [ ! -f "/etc/galaxymediatools.conf" ]; then
 echo -e "No config file found. Exiting."
 exit 1
else
 source /etc/galaxymediatools.conf
fi
if [ "$LOGDIR" == "" ] || [ "$TVDIR" == "" ] || [ "$TRANSDIR" == "" ] || [ "$POAK" == "" ] || [ "$POUK" == "" ] || [ "$SSHINFO" == "" ] || [ "$PLEXCAT" == "" ]; then
echo -e "No config information found in config file. Exiting."
exit 1
fi

cd "$APPDIR"
git pull origin $GITREPO
exit 0

