#!/bin/bash

LOGF="/video/Incoming/logs/musictranscoder.log"
INDEXFIL="/video/Incoming/logs/musictranscoder.idx"
TRANSDIR="/TRANSCODE"

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
        echo " "
        echo "Galaxy Media Tools - Automatic Music Transcoder/ID/Rename/Move/Sort"
        echo " "
        echo "massmusictrans [-h] [-d] [-s] [-nid]"
	echo " "
	echo "-h or --help : Help"
        echo "-s  : Simulate only. Dont apply changes"
        echo "-nid : DO NOT run Beets music Identification (Transcode only)"
        echo "-a  : DO NOT have Beets prompt for changes (Automatic mode)"
        echo "-d  : Use current directory for base of search (instead of /music/process/unsorted)"
        echo " "
        exit 0
fi

if [ "$1" == "-s" ] || [ "$2" == "-s" ] || [ "$3" == "-s"] || [ "$4" == "-s"] ; then SIM="yes"; fi
if [ "$1" == "-nid" ] || [ "$2" == "-nid" ] || [ "$3" == "-nid"] || [ "$4" == "-nid"] ; then BID="no"; fi
if [ "$1" == "-a" ] || [ "$2" == "-a" ] || [ "$3" == "-a"] || [ "$4" == "-a"] ; then BAUTO="yes"; fi

if [ "$1" != "-d" ] && [ "$2" != "-d" ] && [ "$3" != "-d" ] && [ "$4" != "-d" ]; then
SOURCEDIR="/music/process/unsorted"
else
SOURCEDIR=`pwd`
fi

source "/opt/galaxymediatools/functions/prechecknl"

log "INFO" "---> Starting Mass Music Transcoder on $HOSTNAME"
starttimer

if [ -f "$INDEXFIL" ]; then rm -f $INDEXFIL; fi

log "INFO" "Using directory $SOURCEDIR as base for music search."
starttimer2
if [ "$TRANSDIR" == "" ];then
log "ERROR" "ERROR! TRANSDIR is null. Exiting."
exit 1
fi
log "INFO" "Building index of files to process on $THISSERVER"
echo "Building index of files to process..."

find $SOURCEDIR -type f -name *.flac -name *.m4a >> $INDEXFIL
i=0
while read sfile
do
    if [[ -f $sfile ]]; then
        file[$i]=$sfile
        i=$(($i+1))
    fi
done < $INDEXFIL
ELAPSED2=$(elapsed2)
log "INFO" "File index build complete. Elapsed: $ELAPSED2"
log "INFO" "Starting transcode process on ${#file[@]} files on $HOSTNAME"
echo "Starting transcode process on ${#file[@]} files"
pushover "transcoder" "TV Transcoder Starting in $TMODE on $HOSTNAME - ${#file[@]} Files to process"

starttimer2
for f in "${file[@]}"; do
starttimer2
 fil=${f##*/}
 EXT=${f: -3}
 transc=`echo "$f" | cut -d "." -f3`
 transd=`echo "$f" | cut -d "." -f2`
 OSIZE=$(wc -c "$f" | cut -f 1 -d ' ')
 fne="${f%.*}"
 fng="${fne##*/}"
 fleft=$((${#file[@]}-$j))
 echo "Copying file to local drive for transcoding on $fne..."
  log "INFO" "Copying file to local drive for transcoding on $THISSERVER $fne"
 starttimer3
 if [[ -z $SIM ]]; then cp -f "$f" "$TRANSDIR"; fi
 ELAPSED3=$(elapsed3)
 log "INFO" "Copy file to local drive for transcoding complete. Elapsed: $ELAPSED3"
 starttimer3
  log "INFO" "Processing audio file on $THISSERVER - $fil"
  echo "*Processing audio file - $fil..."
   ffmpegsw="-vn -codec:a libmp3lame -qscale:a 2 -ac 2 -f mp3"
  if [[ -z $SIM ]]; then nice -n -10 /usr/local/bin/ffmpeg -i "$TRANSDIR/$fil" $ffmpegsw "$TRANSDIR/$fng.mp3" < /dev/null &> /dev/null; fi
  if [ "$?" != "0" ]; then
   log "ERROR" "Error transcoding audio file $fil. Exiting."
   exit 1
  fi
  ELAPSED3=$(elapsed3)
   log "INFO" "Audio transcode completed successfully on $THISSERVER- Replacing original $fil. Elapsed: $ELAPSED3"
   log "INFO" "Moving transcoded file back to filer on $THISSERVER - $fng.trans.mp4"
   echo "Audio transcode completed successfully. Replacing original $fil. Elapsed: $ELAPSED3"
   if [[ -z $SIM ]]; then
    rm -f "$f"
    mv -f "$TRANSDIR/$fng.mp3" "$fne.mp3"
    rm -f "$TRANSDIR/$fil"
   fi 
done
ELAPSED2=$(elapsed2)

if [[ $BID ]]; then
log "INFO" "All music transcoding complete.  Continuing to music identificationi. Elapsed: $ELAPSED2"

 if [[ $BAUTO ]]; then
   starttimer3
   log "INFO" "Running Beets music organizer..."
   beet -c /opt/galaxymediatools/conf/beetsconfig.yaml import $SOURCEDIR &>> $LOGF
   ELAPSED3=$(elapsed3)
   if [ "$?" != "0" ]; then
    log "ERROR" "Beets DID NOT complete successfully.  Check Log. Elapsed: $ELAPSED3"
   else
    log "INFO" "Beets completed successfully. Elapsed: $ELAPSED3"
    starttimer3
    log "INFO" "Moving remaining files to /music/process/failed_id for further examination"
    mv "$SOURCEDIR/*" "/music/process/failed_id"
    ELAPSED3=$(elapsed3)
    log "INFO" "Remaining files moved to /music/process/failed_id. Elapsed: $ELAPSED3"
   fi
 else
   beet -v -c /opt/galaxymediatools/conf/beetsconfig.yaml import $SOURCEDIR
 fi

else
log "INFO" "Skipping music identification due to command line option -nid. Elapsed: $ELAPSED2"
fi

ELAPSED=$(elapsed)
log "INFO" "<--- Completed Music Transcoder script on $HOSTNAME. Elapsed: $ELAPSED"
