#!/bin/bash

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
        echo " "
        echo "Galaxy Media Tools - Automatic AC3 Movie Transcoder"
	echo " "
	echo "-h or --help : Help"
	echo "-s  : Simulation only"
	echo "-p  : Run a Plex full analyze at end of script"
        echo " "
        exit 0
fi

if [ "$1" == "-s" ] ||  [ "$2" == "-s" ] ||  [ "$3" == "-s" ] ||  [ "$4" == "-s" ]; then SIM="yes"; fi
if [ "$1" == "-p" ] ||  [ "$2" == "-p" ] ||  [ "$3" == "-p" ] ||  [ "$4" == "-p" ]; then PUPD="yes"; fi

source "/opt/galaxymediatools/functions/prechecknl"
source "/opt/galaxymediatools/functions/isinteg"
LOGF="$LOGDIR/MMT_$THISSERVER_$CTS.txt"
INDXFIL="MMT_fileindex_$THISSERVER.txt"
if [[ $SIM ]]; then TMODE="Simulation mode"
elif [[ $REV ]]; then TMODE="Span Reverse mode"
elif [[ $SPN ]]; then TMODE="Span Forward mode"
elif [[ $CURD ]]; then TMODE="Single Directory Mode"
else TMODE="Normal mode"
fi
echo "AC3 Movie Transcoder Starting in $TMODE..."
printf "`eval date +%m/%d/%y"-"%H:%M` - *** AC3 Movie Transcoder in $TMODE Starting on $THISSERVER \n" >> $LOGF
touch $LOGF
echo "Resetting transcode directory $TRANSDIR..."
printf "`eval date +%m/%d/%y"-"%H:%M` - 00 Resetting Transcode directory on $THISSERVER \n" >> $LOGF
if [ "$TRANSDIR" == "" ];then
echo -e "${errorcolor}ERROR! TRANSDIR is null. Exiting."
exit 1
fi
if [ -d $TRANSDIR ]; then
 rm -r $TRANSDIR/* &> /dev/null
else
 mkdir $TRANSDIR
fi
printf "`eval date +%m/%d/%y"-"%H:%M` - 00 Building index of files to process on $THISSERVER \n" >> $LOGF
echo "Building index of files to process..."
if [ -f "$LOGDIR/$INDXFIL" ]; then rm -f $LOGDIR/$INDXFIL; fi

FINDVARS="$MOVIEDIR -type f -name \"*AC3*\""
FCNT=`eval /usr/bin/find "$FINDVARS" | wc -l`

eval /usr/bin/find $FINDVARS | sort  >> $LOGDIR/$INDXFIL
i=0
while read sfile
do
    if [[ -f $sfile ]]; then
        file[$i]=$sfile
        i=$(($i+1))
    fi
done < $LOGDIR/$INDXFIL
printf "`eval date +%m/%d/%y"-"%H:%M` - 00 Starting transcode process on ${#file[@]} files on $THISSERVER \n" >> $LOGF
echo "Starting transcode process on ${#file[@]} files"
if [[ -z $SIM ]]; then $APPDIR/pushover.sh -T $POAK -U $POUK "AC3 Movie Transcoder Starting in $TMODE on $THISSERVER - ${#file[@]} Files to proccess" &> /dev/null; fi
j=1
for f in "${file[@]}"; do
/opt/galaxymediatools/transmovie "$f"
done
TTIME=$(date +%s)
ETIME=$(gettime "$STIME" "$TTIME")
rm -r $TRANSDIR/* &> /dev/null
echo "Starting Plex server Movie section full video analyze..."
printf "`eval date +%m/%d/%y"-"%H:%M` - 00 Plex server full video analyze on $THISSERVER \n" >> $LOGF

if [[ -z $SIM ]] && [[ $PUPD ]]; then ssh $PLEXINFO 'sudo su plex -c "plexscan -b -a -c $PLEXMCAT &> /dev/null &"' &> /dev/null & 
fi
if [[ -z $SIM ]]; then $APPDIR/pushover.sh -T $POAK -U $POUK "AC3 Movie Transcoder Complete on $THISSERVER - Total Elapsed: $ETIME"; fi
printf "`eval date +%m/%d/%y"-"%H:%M` - *** AC3 Movie Transcoder Complete on $THISSERVER- Elapsed Time: $ETIME\n" >> $LOGF
echo "Auto Ac3 Movie Transcode Script Complete."
FTIME=$((TTIME-STIME))
#if [[ ! $SIM ]] && [ $FTIME -gt 10 ]; then 
if [[ -z $SIM ]]; then  pm-suspend
 exit 0
fi
#else
# echo "Problem!! Script terminated to quickly. NOT suspending server"
# printf "`eval date +%m/%d/%y"-"%H:%M` - Problem!! Script terminated to quickly. NOT suspending server $THISSERVER\n" >> $LOGF
# if [[ -z $SIM ]]; then $APPDIR/pushover.sh -T $POAK -U $POUK "Problem!! Script terminated to quickly. NOT suspending server $THISSERVER"; fi
# exit 1
#fi
