#!/bin/bash

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
        echo " "
        echo "Galaxy Media Tools - Automatic TV Transcoder"
	echo " "
	echo "-h or --help : Help"
	echo "-s  : Simulation only"
	echo "-g  : Split list in half (for spanning multiple servers)"
	echo "-gr : Split list in half and reverse (for second spanning server)"
        echo "-d  : Current directory only (bypass date chacks)"
	echo "-p  : Run a Plex full analyze at end of script"
        echo " "
        exit 0
fi

if [ "$1" == "-s" ] ||  [ "$2" == "-s" ] ||  [ "$3" == "-s" ] ||  [ "$4" == "-s" ]; then SIM="yes"; fi
if [ "$1" == "-g" ] ||  [ "$2" == "-g" ] ||  [ "$3" == "-g" ] ||  [ "$4" == "-g" ]; then SPN="yes"; fi
if [ "$1" == "-gr" ] ||  [ "$2" == "-gr" ] ||  [ "$3" == "-gr" ] ||  [ "$4" == "-gr" ]; then REV="yes"; fi
if [ "$1" == "-p" ] ||  [ "$2" == "-p" ] ||  [ "$3" == "-p" ] ||  [ "$4" == "-p" ]; then PUPD="yes"; fi

if [ "$1" == "-d" ]; then CURD="$2"
elif [ "$2" == "-d" ]; then CURD="$3"
elif [ "$3" == "-d" ]; then CURD="$4"
elif [ "$4" == "-d" ]; then CURD="$5"
fi

source "/opt/galaxymediatools/functions/precheck"
source "/opt/galaxymediatools/functions/isinteg"
LOGF="$LOGDIR/tvtranscoder.log"
INDXFIL="tvtranscoder.idx"
if [[ $SIM ]]; then TMODE="Simulation mode"
elif [[ $REV ]]; then TMODE="Span Reverse mode"
elif [[ $SPN ]]; then TMODE="Span Forward mode"
elif [[ $CURD ]]; then TMODE="Single Directory Mode"
else TMODE="Normal mode"
fi
starttimer
echo "TV Show Transcoder Starting in $TMODE..."
log "INFO" "---> TV Show Transcoder in $TMODE Starting on $THISSERVER"
touch $LOGF
echo "Resetting transcode directory $TRANSDIR..."
log "INFO" "Resetting Transcode directory on $THISSERVER"
if [ "$TRANSDIR" == "" ];then
log "ERROR" "ERROR! TRANSDIR is null. Exiting."
exit 1
fi
if [ -d $TRANSDIR ]; then
 rm -r $TRANSDIR/* &> /dev/null
else
 mkdir $TRANSDIR
fi
log "INFO" "Building index of files to process on $THISSERVER"
echo "Building index of files to process..."
starttimer2
if [ -f "$LOGDIR/$INDXFIL" ]; then rm -f $LOGDIR/$INDXFIL; fi

if [[ $CURD ]]; then
FINDVARS="\"$CURD\" -type f ! -name *.ntrans.* ! -name *.trans.* -size +100M"
else
FINDVARS="\"$TVDIR\" -type f ! -path \"$EXPATH1/*\" ! -path \"$EXPATH2/*\" ! -path \"$EXPATH3/*\" ! -path \"$EXPATH4/*\" ! -path \"$EXPATH5/*\" ! -path \"$EXPATH6/*\" ! -path \"$EXPATH7/*\" ! -path \"$EXPATH8/*\" ! -path \"$EXPATH9/*\" ! -name *.ntrans.* ! -name *.trans.* $ATTRANS"
fi
FCNT=`eval /usr/bin/find "$FINDVARS" | wc -l`

if [[ $SPN ]] || [[ $REV ]]; then
FCOUNT1=$((FCNT/2))
FRCOUNT=$((FCNT%2))
if [ "$FRCOUNT" == "0" ]; then 
 FCOUNT2=$FCOUNT1
else
 FCOUNT2=$((FCOUNT1+1))
fi
fi
if [[ $REV ]]; then eval /usr/bin/find $FINDVARS | sort -r | head -$FCOUNT1 >> $LOGDIR/$INDXFIL
elif [[ $SPN ]]; then eval /usr/bin/find $FINDVARS | sort | head -$FCOUNT2 >> $LOGDIR/$INDXFIL
else eval /usr/bin/find $FINDVARS | sort  >> $LOGDIR/$INDXFIL
echo $FINDVARS
fi
i=0
while read sfile
do
    if [[ -f $sfile ]]; then
        file[$i]=$sfile
        i=$(($i+1))
    fi
done < $LOGDIR/$INDXFIL
ELAPSED2=$(elapsed2)
log "INFO" "File index build complete. Elapsed: $ELAPSED2"
log "INFO" "Starting transcode process on ${#file[@]} files on $THISSERVER"
echo "Starting transcode process on ${#file[@]} files"
if [[ -z $SIM ]]; then pushover "transcoder" "TV Transcoder Starting in $TMODE on $THISSERVER - ${#file[@]} Files to process"; fi
j=1
starttimer2
for f in "${file[@]}"; do
 fil=${f##*/}
 EXT=${f: -3}
 transc=`echo "$f" | cut -d "." -f3`
 transd=`echo "$f" | cut -d "." -f2`
 OSIZE=$(wc -c "$f" | cut -f 1 -d ' ')
 fne="${f%.*}"
 fng="${fne##*/}"
 fleft=$((${#file[@]}-$j))
 if [ -f "$fne.trans.mp4" ]; then
  log "WARN" "File already has transcoded version existing on $THISSERVER - removing $fne.trans.mp4"
  echo "File already has transcoded version existing - removing $fne.trans.mp4"
  if [[ -z $SIM ]]; then rm -f "$fne.trans.mp4"; fi
 fi
 starttimer3
 echo "Checking video file integrity of $fne..."
 isinteg "$f"
 if [ "$ISINTEG" == "1" ]; then
  echo -e "File passed video integrity test - $fne"
  ELAPSED3=$(elapsed3)
  log "INFO" "File passed video integrity test on $THISSERVER. Elapsed: $ELAPSED3 - $fne" 
echo "Copying file to local drive for transcoding on $fne..."
  log "INFO" "Copying file to local drive for transcoding on $THISSERVER $fne"
 starttimer3
 if [[ -z $SIM ]]; then cp -f "$f" "$TRANSDIR"; fi
 ELAPSED3=$(elapsed3)
 log "INFO" "Copy file to local drive for transcoding complete. Elapsed: $ELAPSED3"
 starttimer3
  #FRAMES=`/usr/local/bin/ffprobe -select_streams v -show_streams "$TRANSDIR/$fil" 2>/dev/null | grep nb_frames | sed -e 's/nb_frames=//'`
  HEIGHT=`/usr/local/bin/ffprobe -select_streams v -show_streams "$TRANSDIR/$fil" 2>/dev/null | grep coded_height | sed -e 's/coded_height=//'`
  if [ $HEIGHT -gt 406 ]; then
   log "INFO" "Processing video file (Resized) on $THISSERVER - $fil"
   echo "*Processing video file (Resized) - $fil..."
   ffmpegsw="-c:v libx264 -preset slow -sn -crf $TVQUAL -profile:v high -vf scale=720:400 -codec:a aac -ac 2 -ar 44100 -b:a 128k"
   asd="(Resized)"
  else
   log "INFO" "Processing video file (Not-Resized) on $THISSERVER - $fil" 
   echo "*Processing video file (Not-Resized) - $fil..."
   ffmpegsw="-c:v libx264 -preset slow -sn -crf $TVQUAL -profile:v high -codec:a aac -ac 2 -ar 44100 -b:a 128k"
   asd="(Not Resized)"
  fi
  if [[ -z $SIM ]]; then nice -n -10 /usr/local/bin/ffmpeg -i "$TRANSDIR/$fil" $ffmpegsw "$TRANSDIR/$fng.trans.mp4" < /dev/null &> /dev/null; 
  fi
  ELAPSED3=$(elapsed3)
  SOSIZE=$((OSIZE/1000000))
  NSIZE=$(wc -c "$TRANSDIR/$fng.trans.mp4" | cut -f 1 -d ' ')
  SNSIZE=$((NSIZE/1000000))
  echo "Transcoding finished on $THISSERVER, $asd ($SOSIZE->$SNSIZE) elapsed time: $ELAPSED3 - $fleft left."
  log "INFO" "Transcoding Finished on $THISSERVER. ($SOSIZE->$SNSIZE) $fleft Left, Elapsed time: $ELAPSED3 - $fil"
  
  if [ ! -f "$TRANSDIR/$fng.trans.mp4" ]; then
   echo "PROBLEM!! No transcoded file found, something went wrong. Exiting."
   log "ERROR" "PROBLEM!! No transcoded file found, something went wrong on $THISSERVER. Exiting. $fil"
   if [[ -z $SIM ]]; then pushover "transcoder" "PROBLEM!! No transcoded file found, something went wrong on $THISSERVER. Exiting. $fil"; fi
   exit 1
  fi
  
  if [ "$NSIZE" -lt "25000000" ];then
   rm -r "$TRANSDIR/$fne.trans.mp4"
   rm -r "$TRANSDIR/$fil"
   log "ERROR" "PROBLEM!! Transcoded file under 25 Meg, something went wrong on $THISSERVER, Exiting. $fil"
   echo "PROBLEM!! Transcoded file under 25 Meg, something went wrong, Exiting."
   if [[ -z $SIM ]]; then pushover "transcoder" "PROBLEM!! Transcoded file under 25 Meg, something went wrong on $THISSERVER. Exiting. $fil"; fi
   exit 1
  fi
  
  if [ "$OSIZE" -gt "$NSIZE" ] && [ "$NSIZE" -gt "10000000" ]; then
   log "INFO" "Transcoded file is smaller as intended on $THISSERVER- Deleting original $fil"
   log "INFO" "Copying transcoded file back to filer on $THISSERVER - $fng.trans.mp4"
   echo "Transcoded file is smaller as intended, Deleting Original and copying transcoded file back $fng.trans.mp4"
   if [[ -z $SIM ]]; then 
    ((NRESIZE++))
    #$APPDIR/pushover.sh -T $POAK -U $POUK "Transcode Finished on $THISSERVER - $asd ($SOSIZE->$SNSIZE) - $fil Elapsed Time: $GTIME - Original Replaced - $fleft Left." &> /dev/null
    cp -f "$TRANSDIR/$fng.trans.mp4" "$fne.trans.mp4"
    rm -f "$f"
    rm -f "$TRANSDIR/$fng.trans.mp4"
    rm -f "$TRANSDIR/$fil"
   fi 
  else
   if [[ -z $SIM ]]; then rm -f "$TRANSDIR/$fng.trans.mp4"; fi
   log "WARN" "Transcoded file is BIGGER then intended on $THISSERVER - Deleting transcode $fne.trans.mp4"
   log "WARN" "Marking original file non transcodable on $THISSERVER - $fne.ntrans.$EXT" 
   echo "Transcoded file is BIGGER then intended on $THISSERVER - Keeping Original and Deleting transcode $fne.trans.mp4"
   if [[ -z $SIM ]]; then
   ((RESIZE++))
   #$APPDIR/pushover.sh -T $POAK -U $POUK "Transcode Finished on $THISSERVER - $asd ($SOSIZE->$SNSIZE) - $fil Elapsed Time: $GTIME - Original Kept, Non-Transcodable - $fleft Left." &> /dev/null
    mv "$f" "$fne.ntrans.$EXT"
    rm -f "$TRANSDIR/$fil"
    rm -f "$TRANSDIR/$fng.trans.mp4"
   fi
  fi
  echo "Running Plex Server TV Section Scan..."
  if [[ -z $SIM ]]; then curl "http://172.25.1.26:32400/library/sections/$PLEXCAT/refresh?X-Plex-Token=$PLEXTOKEN"
  fi
 else
  echo "File FAILED integrity test!! Purging file and marking for re-download"
  if [[ -z $SIM ]]; then pushover "transcoder" "File FAILED integrity test! on $THISSERVER $fil - Marking for redownload"; fi
  log "WARN" "File failed integrity test on $THISSERVER - $fil"
  log "WARN" "Purging file and marking for re-download on $THISSERVER - $fil"
  if [[ -z $SIM ]]; then 
   printf "`eval date +%m/%d/%y"-"%H:%M` - $f \n" >> "$LOGDIR/re-downloads.txt"
   #mv -f "$f" "$TRASHDIR"
   rm -r "$TRANSDIR/isinteg.$EXT" &> /dev/null
   rm -r "$TRANSDIR/$fil" &> /dev/null
  fi
fi
j=$(($j+1))
done

rm -r $TRANSDIR/* &> /dev/null
echo "Starting Plex server TV section full video analyze..."
log "INFO" "Plex server full video analyze on $THISSERVER"

if [[ -z $SIM ]] && [[ $PUPD ]]; then curl "http://172.25.1.26:32400/library/sections/$PLEXCAT/refresh?X-Plex-Token=$PLEXTOKEN" 
fi
if [[ -z $SIM ]]; then pushover "transcoder" "TV Transcoder Complete. ${#file[@]} episodes processed. $RESIZE Resized, $NRESIZE Not-Resized. Elapsed: $ETIME"; fi
ELAPSED=$(elapsed)
log "INFO" "<--- TV Transcoder Complete on $THISSERVER- Elapsed Time: $ELAPSED"
echo "Auto TV Transcode Script Complete."
exit 0
