#!/bin/bash

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
        echo " "
        echo "Galaxy Tools Master Updater - Full update on all servers"
        echo " "
        echo "-h or --help : Help"
        echo " "
        exit 0
fi

source "/opt/galaxymediatools/functions/prechecknl"

echo -e "${cmd2color}Updating local server ${servercolor}$THISSERVER"
 printf "${soutcolor}"
$APPDIR/functions/masterupdate
printf "${nocolor}"
 fping -c1 -t300 $T1IP 2>/dev/null 1>/dev/null
  if [ "$?" != "0" ]; then
   WASSLEEPING1="1"
   echo -e "${cmd2color}Waking transcode server ${servercolor}$T1NAME"
   printf "${soutcolor}"
   wakeonlan $T1MAC
   printf "${nocolor}"
   sleep 10
   echo -e "${cmd1color}Transcode server ${servercolor}$T1NAME ${cmd1color}started"
  fi
 printf "${soutcolor}"
 ssh $T1INFO "sudo $APPDIR/functions/masterupdate"
 printf "${nocolor}"
  echo -e "${cmd1color}Server ${servercolor}$T1NAME ${cmdcolor}updated"
 if [ "$WASSLEEPING1" == "1" ]; then
  echo -e "${cmd2color}Transcoder server ${servercolor}$T1NAME ${cmd2color}was sleeping, putting back to sleep."
  ssh $T1INFO 'sudo pm-suspend' &
 fi

 fping -c1 -t300 $T2IP 2>/dev/null 1>/dev/null
  if [ "$?" != "0" ]; then
  WASSLEEPING2="1"
   echo -e "${cmd2color}Waking transcode server ${servercolor}$T2NAME"
   printf "${soutcolor}"
   wakeonlan $T2MAC
   printf "${nocolor}"
   sleep 10
   echo -e "${cmd1color}Transcode server ${servercolor}$T2NAME ${cmd1color}started"
  fi
 printf "${soutcolor}"
 ssh $T2INFO "sudo $APPDIR/functions/masterupdate"
  printf "${nocolor}"
  echo -e "${cmd1color}Server ${servercolor}$T2NAME ${cmdcolor}updated"
 if [ "$WASSLEEPING2" == "1" ]; then
  echo -e "${cmd2color}Transcoder server ${servercolor}$T2NAME ${cmd2color}was sleeping, putting back to sleep.${nocolor}"
  ssh $T2INFO 'sudo pm-suspend' &   
fi

if [ "$THISSERVER" != "$MSNAME" ]; then
printf "${soutcolor}"
ssh $MSINFO "sudo $APPDIR/functions/masterupdate"
printf "${nocolor}"
echo -e "${cmd1color}Server ${servercolor}$MSNAME ${cmdcolor}updated"
fi 

if [ "$THISSERVER" != "$DSNAME" ]; then
printf "${soutcolor}"
ssh $DSINFO "sudo $APPDIR/functions/masterupdate"
printf "${nocolor}"
echo -e "${cmd1color}Server ${servercolor}$DSNAME ${cmdcolor}updated"
fi

echo -e "${nocolor}"
