#!/bin/bash

source="/opt/galaxymediatools/functions/prechecknl"

if [[ "$1" == "-u" ]]; then
echo "UN-Mounting USB backup drives..."
umount "$MOUNT1"
umount "$MOUNT2"
echo "USB drives unmounted"
exit 0
else
echo "Mouting USB drives..."
mount UUID="$DUUID1" "$MOUNT1"
mount UUID="$DUUID2" "$MOUNT2"
echo "USB drives mounted"
exit 0
fi

