#!/bin/bash

source=/opt/galaxymediatools/prechecknl

QFEP=`find /video/Movies -type f -name "*480p*"`
#QSD=`find /video/Movies -type f -name "*SD*"`
#THISYEAR=`find /video/Movies -type f -name "*(2016)*"`

echo $QFEP
