#!/bin/bash

LOGF="/video/Incoming/logs/musictranscoder.log"
INDEXFIL="/video/Incoming/logs/musictranscoder.idx"
TRANSDIR="/TRANSCODE"

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
        echo " "
        echo "Galaxy Media Tools - Automatic Music Transcoder/ID/Rename/Move/Sort"
        echo " "
        echo "musictrans [-d]"
	echo " "
	echo "-h or --help : Help"
        echo "-s  : Simulate ony. Dont apply changes"
        echo "-d  : Use current directory for base of search (instead of /video/unsorted)"
        echo " "
        exit 0
fi

if [ "$1" == "-s" ] || [ "$2" == "-s" ]; then SIM="yes"; fi


if [ "$1" != "-d" ] && [ "$2" != "-d" ]; then
SOURCEDIR="/music/unsorted"
else
SOURCEDIR=`pwd`
fi

source "/opt/galaxymediatools/functions/prechecknl"

log "INFO" "---> Starting Mass Music Transcoder"
starttimer

if [ -f "$INDXFIL" ]; then rm -f $INDXFIL; fi

log "INFO" "Using directory $SOURCEDIR as base for music search."
starttimer2
if [ "$TRANSDIR" == "" ];then
log "ERROR" "ERROR! TRANSDIR is null. Exiting."
exit 1
fi
log "INFO" "Building index of files to process on $THISSERVER"
echo "Building index of files to process..."

find $SOURCEDIR -type f -name *.flac -name *.m4a > $INDEXFIL
i=0
while read sfile
do
    if [[ -f $sfile ]]; then
        file[$i]=$sfile
        i=$(($i+1))
    fi
done < $INDEXFIL
ELAPSED2=$(elapsed2)
log "INFO" "File index build complete. Elapsed: $ELAPSED2"
log "INFO" "Starting transcode process on ${#file[@]} files on $HOSTNAME"
echo "Starting transcode process on ${#file[@]} files"
pushover "transcoder" "TV Transcoder Starting in $TMODE on $HOSTNAME - ${#file[@]} Files to process"

starttimer2
for f in "${file[@]}"; do
 fil=${f##*/}
 EXT=${f: -3}
 transc=`echo "$f" | cut -d "." -f3`
 transd=`echo "$f" | cut -d "." -f2`
 OSIZE=$(wc -c "$f" | cut -f 1 -d ' ')
 fne="${f%.*}"
 fng="${fne##*/}"
 fleft=$((${#file[@]}-$j))
 echo "Copying file to local drive for transcoding on $fne..."
  log "INFO" "Copying file to local drive for transcoding on $THISSERVER $fne"
 starttimer3
 if [[ -z $SIM ]]; then cp -f "$f" "$TRANSDIR"; fi
 ELAPSED3=$(elapsed3)
 log "INFO" "Copy file to local drive for transcoding complete. Elapsed: $ELAPSED3"
 starttimer3
  log "INFO" "Processing audio file on $THISSERVER - $fil"
  echo "*Processing audio file - $fil..."
   ffmpegsw="-vn -codec:a libmp3lame -qscale:a 2 -ac 2 -f mp3"
  if [[ -z $SIM ]]; then nice -n -10 /usr/local/bin/ffmpeg -i "$TRANSDIR/$fil" $ffmpegsw "$TRANSDIR/$fng.mp3" < /dev/null &> /dev/null; fi
  if [ "$?" != "0" ]; then
   log "ERROR" "Error transcoding audio file $fil. Exiting."
   exit 1
  fi
  ELAPSED3=$(elapsed3)
   log "INFO" "Audio transcode completed successfully on $THISSERVER- Replacing original $fil. Elapsed: $ELAPSED3"
   log "INFO" "Moving transcoded file back to filer on $THISSERVER - $fng.trans.mp4"
   echo "Audio transcode completed successfully. Replacing original $fil. Elapsed: $ELAPSED3"
   if [[ -z $SIM ]]; then
    rm -f "$f"
    mv -f "$TRANSDIR/$fng.mp3" "$fne.mp3"
    rm -f "$TRANSDIR/$fil"
   fi 
done
ELAPSED=$(elapsed)
log "INFO" "<--- Completed Mass Music Transcoder. Elapsed: $ELAPSED"
