#!/bin/bash

echo -e "${yellow}Please wait...${nocolor}"
/usr/bin/screen -S "massmusictrans" -t "massmusictrans" -dm bash -c "/opt/galaxymediatools/massmusictrans" &
sleep 3
/usr/bin/screen -r
exit 0
