#!/bin/bash

. /opt/galaxymediatools/functions/prechecknl

echo -e "${magenta}Please wait"
/usr/bin/screen -S "massmusictrans" -t "massmusictrans" -dm bash -c "/opt/galaxymediatools/massmusictrans" &
LC=0
while [ $LC -lt 4 ]; do
echo -e "."
sleep 1
((LC++))
done
/usr/bin/screen -r
exit 0
