#!/bin/bash
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/opt/galaxymediatools"
export PATH=$PATH

LOGF="/video/Incoming/logs/plexupgrades.log"

source "/opt/galaxymediatools/functions/prechecknl"

LOOPCOUNT=0
WAITHOURS=2

checkplex() {
PLEXBUSY=`curl -k "https://127.0.0.1:32400/status/sessions?X-Plex-Token=$PLEXTOKEN" | grep 'MediaContainer size="1"' | wc -l`
if [ $PLEXBUSY -ne 0 ]; then
 if [ $LOOPCOUNT -eq 0 ]; then
  log "WARN" "Plex server is busy, postponing plex upgrade..."
 fi
sleep 600
fi
((LOOPCOUNT++))
echo $PLEXBUSY
}

starttimer
log "INFO" "---> Starting Plex Media Server upgrade"
starttimer3
HOURLOOP=$((WAITHOURS * 6))
until [ $LOOPCOUNT -eq $HOURLOOP ]; do
PCHECK=$(checkplex)
if [ $PCHECK -eq 0 ]; then
LOOPCOUNT=$HOURLOOP
fi
done
ELAPSED3=$((elapsed3))
NEWST=$((HOURLOOP-1))
if [ $LOOPCOUNT -gt $NEWST ]; then
log "ERROR" "Plex still busy after $WAITHOURS Hours. Skipping plex upgrade. Elapsed: $ELAPSED3"
exit 1
fi
log "INFO" "Plex is idle. Continuing script. Elapsed: $ELAPSED3"


starttimer2
log "INFO" "Starting Plexupdate updates..."
gitupdate "plexupdate" "/opt/plexupdate"
ELAPSED2=$(elapsed2)
log "INFO" "Plexupdate Updates Complete. Elapsed: $ELAPSED2"

starttimer2
log "INFO" "Starting Plexupdate..."
/opt/plexupdate/plexupdate.sh -d --notify-success --config /etc/plexupdate.conf -u &>> $LOGF
ELAPSED2=$(elapsed2)
log "INFO" "Plexupdate complete. Elapsed: $ELAPSED2"

if [ -f /var/run/reboot-required ]; then
 log "WARN" "Reboot required. Running Plex idle reboot script..."
 /opt/galaxymediatools/plexreboot
else
 log "INFO" "No reboots pending."
fi

ELAPSED=$(elapsed)
log "INFO" "<--- Completed Plex Media Server uggrade. Elapsed: $ELAPSED"

