#!/bin/bash

LOGF="/video/Incoming/logs/plexupgrades.log"

source "/opt/galaxymediatools/functions/prechecknl"

starttimer
log "INFO" "---> Starting Plex Media Server upgrade"
/opt/plexupdate/plexupdate.sh -d --notify-success --config /etc/plexupdate.conf -u &>> $LOGF
ELAPSED=$(elapsed)
log "INFO" "---> Completed Plex Media Server uggrade. Elapsed: $ELAPSED"

