#!/bin/bash
if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
        echo " "
        echo "Galaxy Media Tools - Plex Server section updater"
        echo " "
        echo "-h or --help : Help"
        echo " "
        exit 0
fi

if [ "$1" == "" ]; then
        echo "Argument missing. Specify which plex section to update <movies> <tv>"
        exit 1
fi

source "/opt/galaxymediatools/functions/prechecknl"

if [ "$1" == "movies" ]; then
echo "Sending update notification to Plex Server to update MOVIES"
PLEXC=$PLEXMCAT
elif [ "$1" == "tv" ]; then
echo "Sending update notification to Plex Server to update TV SHOWS"
PLEXC=$PLEXCAT
else
echo "Wrong option specified. use /"tv/" or /"movies/""
exit 1
fi

curl "http://172.25.1.26:32400/library/sections/$PLEXC/refresh?X-Plex-Token=$PLEXTOKEN"

echo "Section is being scanned."
