#!/bin/bash
control_c()
{
  echo -en "\n*** Ouch! Exiting ***\n"
  rm -rf /var/lock/gtrans.lock &> /dev/null
  exit $?
}

appexit()
{
  rm -rf /var/lock/gtrans.lock &> /dev/null
  exit $?
}

function gettime {
TTIME=$(($2 - $1))
MIN=$((TTIME / 60))
HRS=$((MIN / 60))
MINR=$((MIN % 60))
if [ "$HRS" != "0" ]; then
echo -e "$HRS Hours and $MINR Minutes"
else
echo -e "$MIN Minutes"
fi
}

APPDIR="/opt/galaxymediatools"
STIME=$(date +%s)
T1IP=`sed -e 's#.*@\(\)#\1#' <<< "$T1INFO"`
T2IP=`sed -e 's#.*@\(\)#\1#' <<< "$T2INFO"`
CTS=`eval date +%Y%m%d`
cd "$APPDIR"
sleep 3
UPG=$(git pull origin master | grep "Already")
if [ "$UPG" != "Already up-to-date." ]; then
  echo "upgrading"
  git pull origin master
  bash $APPDIR/$APPNAME
  exit 0
else
echo "no upgrade needed"
fi

if [ "$1" == "-u" ]; then
 echo -e "Upgrade only. Exiting"
 exit 0
fi

if [ ! -f "/etc/galaxymediatools.conf" ]; then
 echo -e "No config file found. Exiting."
 exit 1
else
 source /etc/galaxymediatools.conf
fi
if [ "$LOGDIR" == "" ] || [ "$TVDIR" == "" ] || [ "$TRANSDIR" == "" ] || [ "$POAK" == "" ] || [ "$POUK" == "" ] || [ "$SSHINFO" == "" ] || [ "$PLEXCAT" == "" ]; then
echo -e "No config information found in config file. Exiting."
exit 1
fi

if mkdir "/var/lock/gtrans.lock"; then
trap control_c SIGINT
trap appexit EXIT
else
echo -e "Process locked. Lock file detected. Can only run 1 transcode script at a time. Exiting."
printf "Process locked. Lock file detected. Can only run 1 transcode script at a time. Exiting. \n" >> $LOGF
exit 1
fi


