#!/bin/bash

source "/opt/galaxymediatools/functions/prechecknl"

#echo -e "${rred}MAKE SURE TO RUN THIS AS THE SSH USER!!${nocolor}"
echo -e "${cmd1color}This is the ${servercolor}$THISSERVER ${cmd1color}server"

if [ -f "/root/.ssh/id_rsa" ]; then
echo -e "${green}Existing RSA key found.${white}"
else 
echo -e "${red}Existing RSA key NOT FOUND!!${white}"
read -r -p "Would you like to generate new ssh auth keys for this server? [y/N] " response
response=${response,,}    # tolower
if [[ $response =~ ^(yes|y)$ ]]; then
ssh-keygen
else
echo -e "${red}No RSA key. Cannot continue.${white}"
exit 1
fi
fi

if [ -f "/root/.ssh/id_rsa" ]; then
echo -e "${green}Existing GitHub RSA key found.${white}"
else
echo -e "${green}No GitHub key found. Copying key to GitHub key...${white}"
cp -f /root/.ssh/id_rsa /root/.ssh/github_id_rsa 
fi

if [ ! -f "/etc/sudoers.d/galaxymediatools" ]; then
echo -e "${red}checking for proper sudoer file...${white}"
echo "ip ALL = (ALL) NOPASSWD: ALL" > "/etc/sudoers.d/galaxymediatools"
else
echo -e "${green}Existing sudoers file found${white}"
fi

if [ "$THISSERVER" != "$T1NAME" ]; then
echo -e "${cmd1color}Copying ssh keys to the ${servercolor}$T1NAME${cmd1color} server...${soutcolor}"
ssh-copy-id $T1INFO
fi
#if [ "$THISSERVER" != "$T2NAME" ]; then
#ssh-copy-id $T2INFO
#fi
if [ "$THISSERVER" != "$MSNAME" ]; then
echo -e "${cmd1color}Copying ssh keys to the ${servercolor}$MSNAME${cmd1color} server... ${soutcolor}"
ssh-copy-id $MSINFO
fi
if [ "$THISSERVER" != "$DSNAME" ]; then
echo -e "${cmd1color}Copying ssh keys to the ${servercolor}$DSNAME${cmd1color} server... ${soutcolor}"
ssh-copy-id $DSINFO
fi
if [ "$THISSERVER" != "$PLEXNAME" ]; then
echo -e "${cmd1color}Copying ssh keys to the ${servercolor}$PLEXNAME${cmd1color} server...${soutcolor}"
ssh-copy-id $PLEXINFO
fi
echo -e "${nocolor}"
