#!/bin/bash

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
        echo " "
        echo "Galaxy Media Tools - Remote Mass movie renamer"
        echo " "
        echo "-h or --help : Help"
	echo "-i : use IMDB matching"
	echo " "
        exit 0
fi

source "/opt/galaxymediatools/functions/precheck"
source "/opt/galaxymediatools/functions/whichserver"

if [ "$1" == "-i" ] ||  [ "$2" == "-i" ] ||  [ "$3" == "-i" ]; then IMDB="yes"; fi

whichserver

if [ "$WHICHSERVER" == "$T1NAME" ]; then
 echo "Starting remote mass movie renamer on $T1NAME"
 if [[ $IMDB ]]; then
  ssh $T1INFO "sudo screen -dm sudo /opt/galaxymediatools/massmovierenamer -v -i"
 else
 ssh $T1INFO "sudo screen -dm sudo /opt/galaxymediatools/massmovierenamer -v"
 fi
 echo -e "Remote mass movie renamer started on $T1NAME"
 exit 0
elif [ "$WHICHSERVER" == "$T2NAME" ]; then
 echo "Starting remote mass movie renamer on $T2NAME"
 if [[ $IMDB ]]; then
 ssh $T2INFO "sudo screen -dm sudo /opt/galaxymediatools/massmovierenamer -v -i"
 else
 ssh $T2INFO "sudo screen -dm sudo /opt/galaxymediatools/massmovierenamer -v"
 fi
 echo -e "Remote mass movie renamer started on $T2NAME"
 exit 0
elif [ "$WHICHSERVER" == "NONE" ]; then
 echo -e "All servers are busy. Exiting."
fi

