#!/bin/bash

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
        echo " "
        echo "Galaxy Media Tools - Remote Stand-Up Comedy Transcoder"
        echo " "
        echo "-h or --help : Help"
        echo "-g : Span across multiple servers"
	echo "-d : specify directory only . for current directory"
        echo " "
        exit 0
fi

if [ "$1" == "-g" ] ||  [ "$2" == "-g" ] ||  [ "$3" == "-g" ] ||  [ "$4" == "-g" ]; then SPAN="yes"; fi

if [ "$1" == "-d" ]; then CURD="$2"
elif [ "$2" == "-d" ]; then CURD="$3"
elif [ "$3" == "-d" ]; then CURD="$4"
elif [ "$4" == "-d" ]; then CURD="$5"
fi

if [ "$CURD" == "." ]; then CURD="$PWD"; fi

source "/opt/galaxymediatools/functions/prechecknl"
source "/opt/galaxymediatools/functions/whichserver"

whichserver
sendtrans ()
{
echo "Starting remote Stand-Up Comedy Transcode on $1"
if [ "$5" == "g" ]; then
ssh $4 "sudo screen -dm sudo /opt/galaxymediatools/masscomedytrans -g"
echo -e "Remote auto Stand-Up Comedy transcode started in span mode on $1"
elif [ "$5" == "gr" ]; then
ssh $4 "sudo screen -dm sudo /opt/galaxymediatools/masscomedytrans -gr"
echo -e "Remote auto Stand-Up Comedy transcode started in span reverse mode on $1"
elif [ "$5" == "" ]; then
ssh $4 "sudo screen -dm sudo /opt/galaxymediatools/masscomedytrans"
echo -e "Remote auto Stand-Up Comedy transcode started in normal mode on $1"
elif [ "$5" == "c" ]; then
ssh $4 "sudo screen -dm sudo /opt/galaxymediatools/masscomedytrans -d \"$CURD\""
echo -e "Remote auto Stand-Up Comedy transcode started in specified directory mode on $1"
echo "sudo screen -dm sudo /opt/galaxymediatools/masscomedytrans -d \"$CURD\""
else
echo "ERROR in Script. Exiting."
exit 1
fi
}

if [[ $SPAN ]]; then
eval /opt/galaxymediatools/remotewake "$T1NAME"
eval /opt/galaxymediatools/remotewake "$T2NAME"
sleep 10
fping -c1 -t300 $T2IP 2>/dev/null 1>/dev/null
if [ "$?" == "0" ]; then
 if (ssh $T2INFO '[ -d /var/lock/gtrans.lock ]'); then
  echo "$T2NAME server is busy. Need 2 transcode servers to span."
  exit 1
 fi
else
  echo "$T2NAME server is not responding. Need 2 transcode servers to span."
  exit 1
fi
fping -c1 -t300 $T1IP 2>/dev/null 1>/dev/null
if [ "$?" == "0" ]; then
 if (ssh $T1INFO '[ -d /var/lock/gtrans.lock ]'); then
  echo "$T1NAME server is busy. Need 2 transcode servers to span."
  exit 1
 fi
else
  echo "$T1NAME server is not responding. Need 2 transcode servers to span."
  exit 1
fi
echo "2 Transcode servers are ready. Starting split Transcodes..."
sendtrans $T1NAME $T1IP $T1MAC $T1INFO g
sendtrans $T2NAME $T2IP $T2MAC $T2INFO gr
echo "Complete."
exit 0
fi

if [ "$WHICHSERVER" == "$T1NAME" ]; then
TNAME=$T1NAME; TIP=$T1IP; TMAC=$T1MAC; TINFO=$T1INFO
elif [ "$WHICHSERVER" == "$T2NAME" ]; then
TNAME=$T2NAME; TIP=$T2IP; TMAC=$T2MAC; TINFO=$T2INFO
else
echo "All servers busy, try again later."
exit 1
fi

if [[ $CURD ]]; then
sendtrans $TNAME $TIP $TMAC $TINFO c "$CURD"
else
sendtrans $TNAME $TIP $TMAC $TINFO
fi
echo "Complete."
