#!/bin/bash

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
        echo " "
        echo "Galaxy Media Tools - Remote embed subtitles"
        echo " "
        echo "-h or --help : Help"
	echo " "
        exit 0
fi

if [ "$1" == "" ]; then
	 echo "Argument missing. Specify which movie to transcode"
        exit 1
fi

source "/opt/galaxymediatools/functions/precheck"
source "/opt/galaxymediatools/functions/whichserver"

whichserver
if [ "$WHICHSERVER" == "$T1NAME" ]; then
 echo "Starting remote movie transcoder on $T1NAME"
 ssh $T1INFO "sudo screen -dm sudo /opt/galaxymediatools/embedsubs \"$2\" -v"
 echo -e "Remote movie transcoder started on $T1NAME with $2"
 exit 0
elif [ "$WHICHSERVER" == "$T2NAME" ]; then
 echo "Starting remote movie transcoder on $T2NAME"
 ssh $T2INFO "sudo screen -dm sudo /opt/galaxymediatools/embedsubs \"$2\" -v"
 echo -e "Remote movie transcoder started on $T2NAME with $2"
else
echo -e "All servers are busy. Exiting."
exit 1
fi

