#!/bin/bash
APPNAME="remotetrans"

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
        echo " "
        echo "Galaxy Media Tools - Remote Transcoder"
        echo " "
        echo "-h or --help : Help"
        echo "-u : Upgrade from git only"
        echo " "
        exit 0
fi

source /opt/galaxymediatools/precheck

echo "Waking transcode server"
wakeonlan $TSMAC
echo "Waiting for startup..."
sleep 10

echo "Starting remote Auto TransTV."
#ssh $SSHTINFO 'sudo /opt/galaxymediatools/transtv & &> /dev/null' &> /dev/null
echo -e "Remote auto tv transcode started."
