#!/bin/bash

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
        echo " "
        echo "Galaxy Media Tools - Remote Transcoder killer"
        echo " "
	echo "Usage: remotetranstv <server> ALL"
	echo " "
        echo "-h or --help : Help"
        echo "ALL : Kill transcode processes on all servers"
        echo " "
        exit 0
fi

if [ "$1" == "" ]; then
        echo "Argument missing. Specify which server to transcode on or ALL for both"
        exit 1
fi

if [ "$2" != "" ]; then
        echo "Too many arguments. Specify one server to transcode on or ALL for both"
        exit 1
fi

source /opt/galaxymediatools/precheck

checkwake()
{
fping -c1 -t300 $2 2>/dev/null 1>/dev/null
 if [ "$?" != "0" ]; then
  return 3  
 else
  return 2
 fi
}

killtrans()
{
checkwake $1 $2 $3
if [ "$?" == "2" ]; then
echo "Skipping server $1, Server is Sleeping."
return 1
echo "Stopping all transcode processes on $1"
ssh $4 "sudo screen -dm sudo /opt/galaxymediatools/killalltrans"
echo -e "All Transcode processes stopped on $1"
fi
}

if [ "$1" == "ALL" ]; then
killtrans $T1NAME $T1IP $T1MAC $T1INFO 
killtrans $T2NAME $T2IP $T2MAC $T2INFO 
echo "Complete."
exit 0
fi

if [ "$1" == "$T1NAME" ]; then
TNAME=$T1NAME; TIP=$T1IP; TMAC=$T1MAC; TINFO=$T1INFO
elif [ "$1" == "$T1NAME" ];
TNAME=$T2NAME; TIP=$T2IP; TMAC=$T2MAC; TINFO=$T2INFO
else
echo "No server exists with that name"
exit 1
fi

killtrans $TNAME $TIP $TMAC $TINFO
echo "Complete."
