#!/bin/bash

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
        echo " "
        echo "Galaxy Media Tools - Remote Mass TV Integrity Checker"
        echo " "
        echo "-h or --help : Help"
        echo " "
        exit 0
fi

if [ "$1" == "" ]; then
        echo "Argument missing. Specify which server to rename on"
        exit 1
fi

source /opt/galaxymediatools/precheck

if [ "$1" == "$T1NAME" ]; then
fping -c1 -t300 $T1IP 2>/dev/null 1>/dev/null
 if [ "$?" != "0" ]; then
  echo "Waking transcode server $T1NAME"
  wakeonlan $T1MAC
  echo "Waiting for startup..."
  sleep 10
  echo -e "Transcode server $T1NAME started"
 fi
 echo "Starting remote Mass TV Integrity checker on $T1NAME"
 ssh $T1INFO "sudo screen -dm sudo /opt/galaxymediatools/masstvinteg -v"
 echo -e "Remote Mass TV Integrity checker started on $T1NAME"
 exit 0
 elif [ "$1" == "$T2NAME" ]; then
fping -c1 -t300 $T2IP 2>/dev/null 1>/dev/null
 if [ "$?" != "0" ]; then 
  echo "Waking transcode server $T2NAME"
  wakeonlan $T2MAC
  echo "Waiting for startup..."
  sleep 10
  echo -e "Transcode server $T2NAME started"
 fi
 echo "Starting remote MAss TV Integrity Checker on $T2NAME"
 ssh $T2INFO "sudo screen -dm sudo /opt/galaxymediatools/masstvinteg -v"
 echo -e "Remote mass TV Integrity Checker started on $T2NAME"
 exit 0
fi
echo "No server exists with that name"
exit 1

