#!/bin/bash

APPNAME="remotestart"

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
        echo " "
        echo "Galaxy Media Tools - Remote WoL Transcode Server"
        echo " "
        echo "-h or --help : Help"
        echo "-u : Upgrade from git only"
        echo " "
        exit 0
fi

source /opt/galaxymediatools/precheck

echo "Waking transcode server"
wakeonlan $TSMAC
echo -e "Transcode server started"
