#!/bin/bash

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
        echo " "
        echo "Galaxy Media Tools - Remote Movie Transcoder"
        echo " "
	echo "-s : Embed Subtitles in video (For forign Movies)"
        echo "-h or --help : Help"
	echo " "
        exit 0
fi

if [ "$1" == "" ]; then
	 echo "Argument missing. Specify which movie to transcode"
        exit 1
fi

if [ "$2" == "-s" ] ||  [ "$3" == "-s" ] ||  [ "$4" == "-s" ]; then EMBEDSUBS="yes"; fi

source "/opt/galaxymediatools/functions/precheck"
source "/opt/galaxymediatools/functions/whichserver"

whichserver
if [ "$WHICHSERVER" == "$T1NAME" ]; then
 echo "Starting remote movie transcoder on $T1NAME"
 if [[ $EMBEDSUBS ]]; then
  ssh $T1INFO "sudo screen -dm sudo /opt/galaxymediatools/transmovie \"$1\" -s"
 else
  ssh $T1INFO "sudo screen -dm sudo /opt/galaxymediatools/transmovie \"$1\""
 fi
 echo -e "Remote movie transcoder started on $T1NAME with $1"
 exit 0
elif [ "$WHICHSERVER" == "$T2NAME" ]; then
 echo "Starting remote movie transcoder on $T2NAME"
 if [[ $EMBEDSUBS ]]; then
 ssh $T2INFO "sudo screen -dm sudo /opt/galaxymediatools/transmovie \"$1\" -s"
 else
 ssh $T2INFO "sudo screen -dm sudo /opt/galaxymediatools/transmovie \"$1\""
 fi
 echo -e "Remote movie transcoder started on $T2NAME with $1"
else
echo -e "All servers are busy. Exiting."
exit 1
fi

