#!/bin/bash

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
        echo " "
        echo "Galaxy Media Tools - Remote Suspend Transcode Server"
        echo " "
	echo " Usage: <servername> or all for all servers"
	echo " "
        echo "-h or --help : Help"
        echo " "
        exit 0
fi

if [ "$1" == "" ]; then
	echo "Argument missing. Specify which server to suspend or all for all"
	exit 1
fi

source "/opt/galaxymediatools/functions/precheck"

if [ "$1" == "$T1NAME" ] || [ "$1" == "all" ]; then
 fping -c1 -t300 $T1IP 2>/dev/null 1>/dev/null
  if [ "$?" != "0" ]; then
  echo "$T1NAME server already suspended."
 else
  if (ssh $T1INFO '[ -d /var/lock/gtrans.lock ]'); then
   echo "NOT Suspending server $T1NAME, because server is busy"
  else
   echo "Suspending transcode server $T1NAME"
   ssh $T1INFO 'sudo pm-suspend' &
   echo -e "Transcode server $T1NAME suspended"
  fi
 fi
fi

if [ "$1" == "$T2NAME" ] || [ "$1" == "all" ]; then
 fping -c1 -t300 $T2IP 2>/dev/null 1>/dev/null
  if [ "$?" != "0" ]; then
   echo "$T2NAME server already suspended."
 else
  if (ssh $T2INFO '[ -d /var/lock/gtrans.lock ]'); then
   echo "NOT Suspending server $T2NAME, because server is busy"
  else
   echo "Suspending transcode server $T2NAME"
   ssh $T2INFO 'sudo pm-suspend' &
   echo -e "Transcode server $T2NAME suspended"
 fi
 fi
fi
