#!/bin/bash

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
        echo " "
        echo "Galaxy Media Tools - Remote Mass TV Integrity Checker"
        echo " "
        echo "-h or --help : Help"
        echo " "
        exit 0
fi

source "/opt/galaxymediatools/functions/prechecknl"
source "/opt/galaxymediatools/functions/whichserver"

whichserver
if [ "$WHICHSERVER" == "$T1NAME" ]; then
 echo "Starting remote Mass TV Integrity checker on $T1NAME"
 ssh $T1INFO "sudo screen -dm sudo /opt/galaxymediatools/masstvinteg -v"
 echo -e "Remote Mass TV Integrity checker started on $T1NAME"
 exit 0
 elif [ "$WHICHSERVER" == "$T2NAME" ]; then
 echo "Starting remote MAss TV Integrity Checker on $T2NAME"
 ssh $T2INFO "sudo screen -dm sudo /opt/galaxymediatools/masstvinteg -v"
 echo -e "Remote mass TV Integrity Checker started on $T2NAME"
 exit 0
fi
echo "All servers are busy. Try again later."
exit 1

