#!/bin/bash

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
        echo " "
        echo "Galaxy Media Tools - Remote TV Transcoder"
        echo " "
	echo "Usage: remotetranstv <-g> <server>"
	echo " "
        echo "-h or --help : Help"
        echo "-g : Span across multiple servers"
	echo "-c : specify dirctory only . for current directory"
        echo " "
        exit 0
fi

if [ "$1" == "" ] || [ "$1" == "-c" ]; then
        echo "Argument missing. Specify which server to transcode on or -g"
        exit 1
fi

if [ "$1" == "-g" ] ||  [ "$2" == "-g" ] ||  [ "$3" == "-g" ] ||  [ "$4" == "-g" ]; then SPAN="yes"; fi

if [ "$2" == "-c" ]; then CURD="$3"
elif [ "$3" == "-c" ]; then CURD="$4"
elif [ "$4" == "-c" ]; then CURD="$5"
fi

if [ "$CURD" == "." ]; then CURD="$PWD"; fi

source "/opt/galaxymediatools/functions/precheck"

wakeserver()
{
fping -c1 -t300 $2 2>/dev/null 1>/dev/null
 if [ "$?" != "0" ]; then
  echo "Waking transcode server $1"
  wakeonlan $3
  echo "Waiting for startup..."
  sleep 10
  echo -e "Transcode server $1 started"
 else
 echo -e "Transcode server $1 is awake"
 fi
}

sendtrans()
{
wakeserver $1 $2 $3
echo "Starting remote TV Transcode on $1"
if [ "$5" == "g" ]; then
ssh $4 "sudo screen -dm sudo /opt/galaxymediatools/transtv -g"
echo -e "Remote auto tv transcode started in span mode on $1"
elif [ "$5" == "gr" ]; then
ssh $4 "sudo screen -dm sudo /opt/galaxymediatools/transtv -gr"
echo -e "Remote auto tv transcode started in span reverse mode on $1"
elif [ "$5" == "" ]; then
ssh $4 "sudo screen -dm sudo /opt/galaxymediatools/transtv"
echo -e "Remote auto tv transcode started in normal mode on $1"
elif [ "$5" == "c" ]; then
ssh $4 "sudo screen -dm sudo /opt/galaxymediatools/transtv -c \"$CURD\""
echo -e "Remote auto tv transcode started in specified directory mode on $1"
else
echo "ERROR in Script. Exiting."
exit 1
fi
}

if [[ $SPAN ]]; then
sendtrans $T1NAME $T1IP $T1MAC $T1INFO g
sendtrans $T2NAME $T2IP $T2MAC $T2INFO gr
echo "Complete."
exit 0
fi

if [ "$1" == "$T1NAME" ]; then
TNAME=$T1NAME; TIP=$T1IP; TMAC=$T1MAC; TINFO=$T1INFO
elif [ "$1" == "$T2NAME" ]; then
TNAME=$T2NAME; TIP=$T2IP; TMAC=$T2MAC; TINFO=$T2INFO
else
echo "No server exists with that name"
exit 1
fi

if [[ $CURD ]]; then
sendtrans $TNAME $TIP $TMAC $TINFO c "$CURD"
else
sendtrans $TNAME $TIP $TMAC $TINFO
fi
echo "Complete."
