#!/bin/bash

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
        echo " "
        echo "Galaxy Media Tools - Remote Mass movie renamer"
        echo " "
        echo "-h or --help : Help"
	echo " "
        exit 0
fi

source "/opt/galaxymediatools/functions/precheck"
source "/opt/galaxymediatools/functions/whichserver"

whichserver
if [ "$WHICHSERVER" == "$T1NAME" ]; then
 echo "Starting remote mass movie renamer on $T1NAME"
 ssh $T1INFO "sudo screen -dm sudo /opt/galaxymediatools/massmovierenamer -v -f"
 echo -e "Remote mass movie renamer started on $T1NAME"
 exit 0
elif [ "$WHICHSERVER" == "$T2NAME" ]; then
 echo "Starting remote mass movie renamer on $T2NAME"
 ssh $T2INFO "sudo screen -dm sudo /opt/galaxymediatools/massmovierenamer -v -f"
 echo -e "Remote mass movie renamer started on $T2NAME"
 exit 0
elif [ "$WHICHSERVER" == "NONE" ]; then
 echo -e "All servers are busy at the moment. Exiting."
fi

