#!/bin/bash

source "/opt/galaxymediatools/functions/precheck"
source "/opt/galaxymediatools/functions/isinteg"
LOGF="$LOGDIR/FRN_$THISSERVER_$CTS.txt"
INDXFIL="FRN_fileindex_$THISSERVER.txt"


printf "`eval date +%m/%d/%y"-"%H:%M` - 00 Building index of files to process \n" >> $LOGF
echo "Building file index..."
sleep 5
if [ -f "$LOGDIR/$INDXFIL" ]; then
 rm -f $LOGDIR/$INDXFIL
fi
find "." -type f | sort >> $LOGDIR/$INDXFIL
i=0
while read sfile
do
    if [[ -f $sfile ]]; then
        file[$i]=$sfile
        i=$(($i+1))
    fi
done < $LOGDIR/$INDXFIL
printf "`eval date +%m/%d/%y"-"%H:%M` - 00 Sending Pushover script start-up notification\n" >> $LOGF
if [[ -z $VERB ]]; then echo "Processing Video Files..."; fi
j=0
for f in "${file[@]}"; do
 fil=${f##*/}
 EXT=${f: -3}
echo $fil
done

