#!/bin/bash

/opt/galaxymediatools/pushover.sh -T "am4StBRZHw1AFGEkPGdLbh8WHjvf3K" -U "ut5A4ejy2dY6HgVBeEaouYHw6uUFpH" "Anti-Virus Scan Started" &> /dev/null

clamscan -r --exclude-dir=/video/Incoming/infected --move=/video/Incoming/infected /video/Incoming

/opt/galaxymediatools/pushover.sh -T "am4StBRZHw1AFGEkPGdLbh8WHjvf3K" -U "ut5A4ejy2dY6HgVBeEaouYHw6uUFpH" "Anti-Virus Scan Ended" &> /dev/null
