#!/bin/bash

if mount|grep "/video" > /dev/null; then
MDIR="/video/Movies/"
#find $MDIR -mindepth 2 -type f -print -exec mv {} . \;
find $MDIR -type d -empty -exec rmdir {} \;
rm $MDIR*.nfo >> /dev/null 2>&1
rm $MDIR*.txt >> /dev/null 2>&1
rm $MDIR*.jpg >> /dev/null 2>&1
rm $MDIR*.gif >> /dev/null 2>&1
rm $MDIR*.idx >> /dev/null 2>&1
rm $MDIR*.sub >> /dev/null 2>&1
rm $MDIR*.srt >> /dev/null 2>&1
rm $MDIR*.exe >> /dev/null 2>&1
rm $MDIR*.me >> /dev/null 2>&1
rm $MDIR*sample* >> /dev/null 2>&1
rm $MDIR*unknown.ignore >> /dev/null 2>&1
/opt/galaxymediatools/resetpermissions
else
exit
fi
