#!/bin/bash

if mountpoint -q /video
then
LOGF="/video/Incoming/logs/securityscan-$HOSTNAME.log"
else
LOGF="/var/log/SECURITYSCAN.log"
fi

source "/opt/galaxymediatools/functions/prechecknl"

starttimer
log "INFO" "---> security scan starting on \"$HOSTNAME\""

log "INFO" "Running system updates..."
starttimer2
apt-get update &> /dev/null
apt-get upgrade -y --allow-downgrades --allow-remove-essential --allow-change-held-packages &>> $LOGF
apt-get autoremove -y &>> $LOGF
log "INFO" "Updates Complete. Elapsed: $ELAPSED2"

if [ "$HOSTNAME" == "$MSNAME" ]; then
starttimer2
log "INFO" "PlexPy Updating.."
gitupdate "plexpy" "/opt/plexpy"
ELAPSED2=$(elapsed2)
log "INFO" "PlexPy Updates Complete. Elapsed: $ELAPSED2"
starttimer2
gitupdate "headphones" "/usr/local/headphones"
ELAPSED2=$(elapsed2)
log "INFO" "Headphones Updates Complete. Elapsed: $ELAPSED2"
starttimer2
gitupdate "sickrage" "/opt/sickrage"
ELAPSED2=$(elapsed2)
log "INFO" "Sickrage Updates Complete. Elapsed: $ELAPSED2"
fi

starttimer2
log "INFO" "Running Chkrootkit..."
/usr/sbin/chkrootkit -n | grep 'INFECTED|Vulnerable'
    if [ $? -eq 0 ]; then
      /opt/galaxymediatools/pushover.sh -T "am4StBRZHw1AFGEkPGdLbh8WHjvf3K" -U "ut5A4ejy2dY6HgVBeEaouYHw6uUFpH" "Security threat from chkrootkit found on $HOSTNAME" &> /dev/null
    CHKEXIT="Threat Found!!"
    else
    CHKEXIT="No Threats Found."
    fi
ELAPSED2=$(elapsed2)
log "INFO" "Chkrootkit Updates Complete. Elapsed: $ELAPSED2"

starttimer2
log "INFO" "Running Lynis..."
/usr/sbin/lynis audit system --cronjob --quiet &>> $LOGF
    if [ $? -ne 0 ]; then
      /opt/galaxymediatools/pushover.sh -T "am4StBRZHw1AFGEkPGdLbh8WHjvf3K" -U "ut5A4ejy2dY6HgVBeEaouYHw6uUFpH" "Lynis Execution error on $HOSTNAME. Check $LOGF" &> /dev/null
    LYNEXIT="Execution Error!!"
    else
    LYNEXIT="Success"
    fi
ELAPSED2=$(elapsed2)
log "INFO" "Lynis Complete. Elapsed: $ELAPSED2"

starttimer2
log "INFO" "Running Antivirs/Malware definition update..."
/opt/sophos-av/bin/savupdate &>> $LOGF
    if [ $? -ne 0 ]; then
      /opt/galaxymediatools/pushover.sh -T "am4StBRZHw1AFGEkPGdLbh8WHjvf3K" -U "ut5A4ejy2dY6HgVBeEaouYHw6uUFpH" "Sophos definition update error on $HOSTNAME. Check $LOGF" &> /dev/null
    SUEXIT="Update Error!!"
    else
    SUEXIT="Success"
    fi
ELAPSED2=$(elapsed2)
log "INFO" "Sophos Definition Updates Complete. Elapsed: $ELAPSED2"

starttimer2
log "INFO" "Running Antivirus/Malware scan..."
/usr/local/bin/savscan -s -narchive -suspicious --stay-on-machine --skip-special / >> $LOGF

if [ $? -eq 0 ]; then
  SAVCODE="Success"
else
  if [ $? -eq 1 ]; then
    SAVCODE="Warning (Possible skipped file)"
  else
    if [ $? -eq 2 ]; then
      SAVCODE="Scan Error"
      pushover "security" "Sophos Execution error on $HOSTNAME. Check $LOGF"
  else
    if [ $? -eq 3 ]; then
      SAVCODE="Threat Found!!"
      pushover "security" "Security Threat Found on $HOSTNAME. Check $LOGF"
    fi
    fi
  fi
fi
ELAPSED2=$(elapsed2)
log "INFO" "Antivirus/Malware scan complete. Elapsed: $ELAPSED2"
ELAPSED=$(elapsed)
echo "* Chkrootkit result: $CHKEXIT" >> $LOGF
echo "* Lynis result: $LYNEXIT" >> $LOGF
echo "* Sophos definition update result: $SUEXIT" >> $LOGF
echo "* Sophos scan result: $SAVCODE" >> $LOGF

REBOO=0

if [ "$HOSTNAME" != "$PLEXNAME" && "$HOSTNAME" != "astroid2" ]; then
if [ -f /var/run/reboot-required ]; then
 log "WARN" "Reboot required. Rebooting"
 REBOO=1
fi
fi

log "INFO" "<--- Security scan completed on \"$HOSTNAME\" Elapsed: $ELAPSED"

if [[ $HOSTNAME == "astroid2" ]]; then
/opt/galaxymediatools/galaxy_maintenance
fi

if [ $REBOO -eq 1 ]; then
/sbin/reboot
fi

exit 0
