#!/bin/bash

if mountpoint -q /video
then
LOGF="/video/Incoming/logs/securityscan-$HOSTNAME.log"
else
LOGF="/var/log/SECURITYSCAN.log"
fi

source "/opt/galaxymediatools/functions/prechecknl"

STIME=`date +%m/%d/%y" "%l:%M%P`
log "INFO" "---> security scan starting on \"$HOSTNAME\""

log "INFO" "Running system updates..."
apt-get update &> /dev/null
apt-get upgrade -y --allow-downgrades --allow-remove-essential --allow-change-held-packages &>> $LOGF
apt-get autoremove -y &>> $LOGF

if [ "$HOSTNAME" == "$MSNAME" ]; then
gitupdate "plexpy" "/opt/plexpy"
gitupdate "headphones" "/usr/local/headphones"
gitupdate "sickrage" "/opt/sickrage"
fi

if [ "$HOSTNAME" == "$PLEXNAME" ]; then
gitupdate "plexupdate" "/opt/plexupdate"
fi

log "INFO" "Running Chkrootkit..."
/usr/sbin/chkrootkit -n | grep 'INFECTED|Vulnerable'
    if [ $? -eq 0 ]; then
      /opt/galaxymediatools/pushover.sh -T "am4StBRZHw1AFGEkPGdLbh8WHjvf3K" -U "ut5A4ejy2dY6HgVBeEaouYHw6uUFpH" "Security threat from chkrootkit found on $HOSTNAME" &> /dev/null
    CHKEXIT="Threat Found!!"
    else
    CHKEXIT="No Threats Found."
    fi

log "INFO" "Running Lynis..."
/usr/sbin/lynis audit system --cronjob --quiet &>> $LOGF
    if [ $? -ne 0 ]; then
      /opt/galaxymediatools/pushover.sh -T "am4StBRZHw1AFGEkPGdLbh8WHjvf3K" -U "ut5A4ejy2dY6HgVBeEaouYHw6uUFpH" "Lynis Execution error on $HOSTNAME. Check $LOGF" &> /dev/null
    LYNEXIT="Execution Error!!"
    else
    LYNEXIT="Success"
    fi

log "INFO" "Running Antivirs/Malware definition update..."
/opt/sophos-av/bin/savupdate &>> $LOGF
    if [ $? -ne 0 ]; then
      /opt/galaxymediatools/pushover.sh -T "am4StBRZHw1AFGEkPGdLbh8WHjvf3K" -U "ut5A4ejy2dY6HgVBeEaouYHw6uUFpH" "Sophos definition update error on $HOSTNAME. Check $LOGF" &> /dev/null
    SUEXIT="Update Error!!"
    else
    SUEXIT="Success"
    fi

log "INFO" "Running Antivirs/Malware scan..."
/usr/local/bin/savscan -s -narchive -suspicious --stay-on-machine --skip-special / >> $LOGF

if [ $? -eq 0 ]; then
  SAVCODE="Success"
else
  if [ $? -eq 1 ]; then
    SAVCODE="Warning (Possible skipped file)"
  else
    if [ $? -eq 2 ]; then
      SAVCODE="Scan Error"
      pushover "security" "Sophos Execution error on $HOSTNAME. Check $LOGF"
  else
    if [ $? -eq 3 ]; then
      SAVCODE="Threat Found!!"
      pushover "security" "Security Threat Found on $HOSTNAME. Check $LOGF"
    fi
    fi
  fi
fi
TTIME=$(date +%s)
   ETIME=$(gettime "$STIME" "$TTIME")
echo "* Chkrootkit result: $CHKEXIT" >> $LOGF
echo "* Lynis result: $LYNEXIT" >> $LOGF
echo "* Sophos definition update result: $SUEXIT" >> $LOGF
echo "* Sophos scan result: $SAVCODE" >> $LOGF
log "INFO" "<--- Security scan completed on \"$HOSTNAME\" Elapsed: $ETIME --------"

if [[ $HOSTNAME == "astroid2" ]]; then
/opt/galaxymediatools/galaxy_maintenance
fi

exit 0
