#!/bin/bash

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
        echo " "
        echo "Galaxy Media Tools - Transcode Server Status"
        echo " "
        echo "-h or --help : Help"
        echo "-u : Upgrade from git only"
        echo " "
        exit 0
fi

source "/opt/galaxymediatools/functions/prechecknl"

declare -A SERVERS

SERVERS[0,0]=$MSNAME
SERVERS[0,1]=$MSIP

SERVERS[1,0]=$DSNAME
SERVERS[1,1]=$DSIP

SERVERS[2]=$PLEXNAME
SERVERS[3]=$T1NAME

for SERVER in "${SERVERS[@]}"
do
echo " "
echo -e "${cmd1color}Checking ${servercolor}${SERVER^^}${cmd1color} Server Status..."
 fping -c1 -t300 $MSIP 2>/dev/null 1>/dev/null
  if [ "$?" == "0" ]; then
   if (ssh $T1INFO '[ -d /var/lock/gtrans.lock ]'); then
   MSST="${yellow}TRANSCODING"
   else
   MSST="${blue}IDLE"
 fi
 echo -e "${servercolor}${MSNAME^^}${cmd1color} Server is ${green}UP ${cmd1color}and $MSST."
 else
  echo -e "${servercolor}${MSNAME^^}${cmd1color} Server is ${red}DOWN."
 fi
echo -e "${nocolor}"
done
