#!/bin/bash

HOSTS[0]="mercury"


HOSTLINE[0]="172.25.1.18	mercury"

insertline() {
SRVR=`cat /etc/hosts | grep "$1"`
if [ $HOSTNAME != "$1" ] && [ $SRVR == 0 ]; then
echo $2 >> /etc/hosts
else
echo "$1 is this host or already exists."
fi
}

for CHOST in "${HOSTS[@]}"
do

done
