#!/bin/bash

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
        echo " "
        echo "Galaxy Media Tools - Transcode Server Status"
        echo " "
        echo "-h or --help : Help"
        echo "-u : Upgrade from git only"
        echo " "
        exit 0
fi

source /opt/galaxymediatools/precheck

echo " "
echo -e "Checking $T1NAME Server Status..."
 fping -c1 -t300 $T1IP 2>/dev/null 1>/dev/null
  if [ "$?" == "0" ]; then
   if (ssh $T1INFO '[ -d /var/lock/gtrans.lock ]'); then
   T1ST="PROCESSING"
   else
   T1ST="IDLE"
 fi
 echo "$T1NAME server is UP and $T1ST."
 else
  echo "$T1NAME Server is DOWN."
 fi

echo " "
echo -e "Checking $T2NAME Server Status..."
 fping -c1 -t300 $T2IP 2>/dev/null 1>/dev/null
  if [ "$?" == "0" ]; then
   if (ssh $T2INFO '[ -d /var/lock/gtrans.lock ]'); then
   T2ST="PROCESSING"
   else
   T2ST="IDLE"
 fi
 echo "$T2NAME server is UP and $T2ST."
 else
  echo "$T2NAME Server is DOWN."
 fi
echo " "
