#!/bin/bash

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
        echo " "
        echo "Galaxy Media Tools - Transcode Server Status"
        echo " "
        echo "-h or --help : Help"
        echo "-u : Upgrade from git only"
        echo " "
        exit 0
fi

source "/opt/galaxymediatools/functions/prechecknl"
echo " "
echo -e "${cmd1color}Checking ${servercolor}$T1NAME ${cmd1color}Server Status..."
 fping -c1 -t300 $T1IP 2>/dev/null 1>/dev/null
  if [ "$?" == "0" ]; then
   if (ssh $T1INFO '[ -d /var/lock/gtrans.lock ]'); then
   T1ST="${yellow}PROCESSING"
   else
   T1ST="${blue}IDLE"
 fi
 echo -e "${servercolor}$T1NAME ${cmd1color}server is ${green}UP ${cmd1color}and $T1ST."
 else
  echo -e "${servercolor}$T1NAME ${cmd1color}Server is ${red}DOWN."
 fi

echo " "
echo -e "${cmd1color}Checking ${servercolor}$T2NAME ${cmd1color}Server Status..."
 fping -c1 -t300 $T2IP 2>/dev/null 1>/dev/null
  if [ "$?" == "0" ]; then
   if (ssh $T2INFO '[ -d /var/lock/gtrans.lock ]'); then
   T2ST="${yellow}PROCESSING"
   else
   T2ST="${blue}IDLE"
 fi
 echo -e "${servercolor}$T2NAME ${cmd1color}server is ${green}UP ${cmd1color}and $T2ST."
 else
  echo -e "${servercolor}$T2NAME ${cmd1color}Server is ${red}DOWN."
 fi
echo -e "${nocolor}"
