#!/bin/bash

source "/opt/galaxymediatools/functions/prechecknl"

if [ "$HOSTNAME" != "$MSNAME" ]; then
 if [ "$1" == "-b" ]; then
  /usr/sbin/ntpdate $MSIP
 else
  /usr/sbin/ntpdate -b $MSIP
 fi
fi

cd /opt/galaxymediatools
./gitpull
