#!/bin/bash

source "/opt/galaxymediatools/functions/prechecknl"

LOGF="/video/Incoming/logs/timesync.log"

if [ "$HOSTNAME" == "$MSNAME" ]; then
/usr/bin/ntpq -np &>> $LOGF
fi

if [ "$HOSTNAME" != "$MSNAME" ]; then
 if [ "$1" == "-b" ]; then
  /usr/sbin/ntpdate $MSIP &>> $LOGF
 else
  /usr/sbin/ntpdate -b $MSIP &>> $LOGF
 fi
fi

