#!/bin/bash

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
        echo " "
        echo "Galaxy Media Tools - Embed Subtitles on Video"
	echo " "
	echo "-s : Embed Subtitles into Video (For forign movies)"
        echo "-d : Downgrade movie from 1080p to 720p"
	echo "-i : Dont check file for integrity eg. mpg files"
	echo "-h or --help : Help"
        echo " "
        exit 0
fi

if [ "$1" == "" ]; then
        echo "Argument missing. Specify a movie to transcode"
        exit 1
fi

if [ "$2" == "-s" ] ||  [ "$3" == "-s" ] ||  [ "$4" == "-s" ]; then EMBEDSUBS="yes"; fi
if [ "$2" == "-d" ] ||  [ "$3" == "-d" ] ||  [ "$4" == "-d" ]; then DOWNGRADE="yes"; fi
if [ "$2" == "-i" ] ||  [ "$3" == "-i" ] ||  [ "$4" == "-i" ]; then NOISINTEG="yes"; fi

source "/opt/galaxymediatools/functions/precheck"
source "/opt/galaxymediatools/functions/isinteg"
source "/opt/galaxymediatools/functions/movierename"
LOGF="$LOGDIR/MVT_$THISSERVER_$CTS.txt"
echo "Script starting up"
touch $LOGF 
printf "`eval date +%m/%d/%y"-"%H:%M` - *** Script Start \n" >> $LOGF
if [ "$TRANSDIR" == "" ];then
echo -e "${errorcolor}ERROR! TRANSDIR is null. Exiting."
exit 1
fi
if [ ! -d $TRANSDIR ]; then
 mkdir $TRANSDIR
fi
if [ "$TRANSDIR" == "" ]; then
echo "TRANSDIR var empty. exiting"
exit 1
fi
rm -f /$TRANSDIR/*
fwewp="$1"
fwenp=${1##*/}
fnewp="${1%.*}"
fnenp="${fwenp%.*}"
EXT=${1: -3}
if [ "NOISINTEG" != "yes" ]; then
echo -e "Checking video file integrity"
isinteg "$1"
else
ISINTEG="1"
fi
if [ "$ISINTEG" == "1" ]; then
 echo -e "Video file passed integrity test."
 printf "`eval date +%m/%d/%y"-"%H:%M` - 06 File passed video integrity test - $fwewp\n" >> $LOGF
 echo "Copying File Locally..."
 printf "`eval date +%m/%d/%y"-"%H:%M` - 04 Copying file from filer to local for transcoding $fwewp\n" >> $LOGF
 cp -f "$fwewp" "$TRANSDIR"
 OSIZE=$(wc -c "$TRANSDIR/$fwenp" | cut -f 1 -d ' ')
 FRAMES=`ffprobe -select_streams v -show_streams "$TRANSDIR/$fwenp" 2>/dev/null | grep nb_frames | sed -e 's/nb_frames=//'`
 WIDTH=`ffprobe -select_streams v -show_streams "$TRANSDIR/$fwenp" 2>/dev/null | grep width | sed -e 's/width=//'` 

if [[ $EMBEDSUBS ]]; then
 printf "`eval date +%m/%d/%y"-"%H:%M` - 01 Processing video file $FRAMES frames (Embedding Subs) - $fwenp\n" >> $LOGF
 $APPDIR/pushover.sh -T $POAK -U $POUK "Processing Movie on $THISSERVER, $FRAMES frames (Embedding Subs) - $fwenp" &> /dev/null
 if [ "$EXT" == "mkv" ]; then
  ffmpegsw="-vf subtitles="$TRANSDIR/PROCFILE.$EXT" -c:v libx264 -preset slow -sn -crf $MOVIEQUAL -profile:v high -codec:a libfaac -ac 2 -ar 44100 -b:a 128k"
 else
  if [ -f "$fnewp.srt" ]; then
   cp -f "$fnewp.srt" "/$TRANSDIR/PROCFILE.srt"
   ffmpegsw="-vf subtitles="/$TRANSDIR/PROCFILE.srt" -c:v libx264 -preset slow -sn -crf $MOVIEQUAL -profile:v high -codec:a libfaac -ac 2 -ar 44100 -b:a 128k"
  else
   echo "No subtitles file found, and not a mkv. Exiting."
   printf "`eval date +%m/%d/%y"-"%H:%M` - 87 No subtitles file found, and not a mkv. Exiting. $fwenp\n" >> $LOGF
  fi
 fi
elif [[ $DOWNGRADE ]]; then
 if [ "$WIDTH" -gt "1290" ]; then
  printf "`eval date +%m/%d/%y"-"%H:%M` - 01 Processing video file $FRAMES frames (1080p to 720p) - $fwenp\n" >> $LOGF
  $APPDIR/pushover.sh -T $POAK -U $POUK "Processing Movie on $THISSERVER, $FRAMES frames (1080p to 720p) - $fwenp" &> /dev/nul
  ffmpegsw="-c:v libx264 -preset slow -sn -crf $MOVIEQUAL -profile:v high -s hd720 -codec:a libfaac -ac 2 -ar 44100 -b:a 128k"
 else
  printf "`eval date +%m/%d/%y"-"%H:%M` - 88 Video file already 720p or lower. Exiting." >> $LOGF
  exit 1
 fi
else
 ffmpegsw="-c:v libx264 -preset slow -sn -crf $MOVIEQUAL -profile:v high -codec:a libfaac -ac 2 -ar 44100 -b:a 128k"
printf "`eval date +%m/%d/%y"-"%H:%M` - 01 Processing video file - $fwenp\n" >> $LOGF
 $APPDIR/pushover.sh -T $POAK -U $POUK "Processing Movie on $THISSERVER, $FRAMES frames - $fwenp" &> /dev/null
fi
   TSTIME=$(date +%s)
   mv -f "$TRANSDIR/$fwenp" "$TRANSDIR/PROCFILE.$EXT"
   echo -e "* Transcoding file: $fwenp"
   nice -n -10 ffmpeg -i "$TRANSDIR/PROCFILE.$EXT" $ffmpegsw "$TRANSDIR/$fnenp.trans.mp4" < /dev/null &> /dev/null 
   TETIME=$(date +%s)
   GTIME=$(gettime "$TSTIME" "$TETIME")
   SOSIZE=$((OSIZE/1000000))
   NSIZE=$(wc -c "$TRANSDIR/$fnenp.trans.mp4" | cut -f 1 -d ' ')
   SNSIZE=$((NSIZE/1000000))
   printf "`eval date +%m/%d/%y"-"%H:%M` - 02 Movie Transcoding Finished. ($SOSIZE->$SNSIZE) Elapsed time: $GTIME - $fwenp \n" >> $LOGF
   if [ ! -f "$TRANSDIR/$fnenp.trans.mp4" ]; then
    echo -e "PROBLEM!! No transcoded file found, something is wrong. Exiting."
    printf "`eval date +%m/%d/%y"-"%H:%M` - 99 PROBLEM!! No transcoded file found, something went wrong. Exiting. $fwenp\n" >> $LOGF
    exit 1
   fi
   if [ "$NSIZE" -lt "400000000" ];then
    rm -r "$TRANSDIR/$fnenp.trans.mp4"
    rm -r "$TRANSDIR/$fwenp"
    printf "`eval date +%m/%d/%y"-"%H:%M` - 98 PROBLEM!! Transcoded file under 400 Meg, something went wrong, Exiting. $fwenp\n" >> $LOGF
    echo -e "PROBLEM!! Transcoded file under 600 Meg, something went wrong, Exiting."
    exit 1
   fi

   printf "`eval date +%m/%d/%y"-"%H:%M` - 02 - Renaming Movie - $fwenp\n" >> $LOGF
   echo "Renaming Movie..."
   mv "$TRANSDIR/$fnenp.trans.mp4" "$TRANSDIR/$fnenp.mp4"
   movierename "$TRANSDIR/$fnenp.mp4"

   echo -e "Copying transcoded file back $renamedmovienp"
   printf "`eval date +%m/%d/%y"-"%H:%M` - 03 Copying transcoded file back to filer - $renamedmovienp\n" >> $LOGF
   cp -f "$TRANSDIR/$fnenp.mp4" "$MOVIEDIR/$renamedmovienp"
   mv -f "$fwewp" "$OLDTRANSDIR"
   rm -f "$TRANSDIR/$fnenp.mp4"
   rm -f "$TRANSDIR/$fwenp"
   echo -e "Transcoding finished, ($SOSIZE->$SNSIZE) Original replaced, elapsed time: $GTIME"
   $APPDIR/pushover.sh -T $POAK -U $POUK "Movie Transcode Finished on $THISSERVER ($SOSIZE->$SNSIZE) - $fwenp Elapsed Time: $GTIME" &> /dev/null
   ssh $SSHINFO -q 'sudo su plex -c "plexscan -s -c $PLEXMCAT &> /dev/null &"' &> /dev/null &
  else
   echo "File FAILED integrity test!! Purging file and marking for re-download"
  $APPDIR/pushover.sh -T $POAK -U $POUK "File failed integrity test!! $fwenp - Marking for redownload"
  printf "`eval date +%m/%d/%y"-"%H:%M` - 67 File failed integrity test - $fwenp \n" >> $LOGF
  printf "`eval date +%m/%d/%y"-"%H:%M` - 68 Purging file and marking for re-download - $fwenp \n" >> $LOGF
  printf "$fwewp \n" >> "$LOGDIR/re-downloads.txt"
  mv -f "$fwewp" "$TRASHDIR"
  fi
  rm -r "$TRANSDIR/$fwenp" &> /dev/null
  TTIME=$(date +%s)
  ETIME=$(gettime "$STIME" "$TTIME")
  printf "`eval date +%m/%d/%y"-"%H:%M` - ***Script End - Elapsed Time: $ETIME\n" >> $LOGF
  echo "Script ended."
  pm-suspend
