#!/bin/bash

source "/opt/galaxymediatools/functions/prechecknl"

if [[ "$1" == "-u" ]]; then
echo "UN-Mounting USB backup drives..."
umount "$MOUNT1"
umount "$MOUNT2"
#echo "Putting USB drives to sleep..."
#hd-idle -t sdc
#hd-idle -t sdb
echo "USB drives unmounted"
exit 0
else

#echo "Waking up USB drives..."
#/opt/galaxymediatools/usbreset /dev/bus/usb/004/003
#/opt/galaxymediatools/usbreset /dev/bus/usb/004/002

echo "Mouting USB drives..."
echo "UUID: $DUUID1 Mountpoint: $MOUNT1"
ntfsfix /dev/disk/by-uuid/$DUUID1
mount UUID="$DUUID1" "$MOUNT1"
echo "UUID: $DUUID2 Mountpoint: $MOUNT2"
ntfsfix /dev/disk/by-uuid/$DUUID2
mount UUID="$DUUID2" "$MOUNT2"
echo "USB drives mounted"
cd /mnt
exit 0
fi

