#!/bin/bash

source "/opt/galaxymediatools/functions/prechecknl"

LOGF="/export/incoming/logs/backupmaster.log"

backupcomplete() {
ELAPSED2=$(elapsed2)
if [ $? -eq 0 ]; then
log "INFO" "$1 Library backup completed successfully. Elapsed: $ELAPSED2"
echo "0"
else
log "ERROR" "$1 Library backup failed. Elapsed: $ELAPSED2"
echo "1"
fi
}

starttimer
log "INFO" "Screened BackupLauncher script starting..."

if mountpoint -q $MOUNT1
then
log "WARN" "Backup1 was mounted already, unmouting for health checks"
umount $MOUNT1
fi

if mountpoint -q $MOUNT2
then
log "WARN" "Backup2 was mounted already, unmouting for health checks"
umount $MOUNT2
fi

#starttimer3
#log "INFO" "SMART drive check starting on $MOUNT1"
#smartctl -T permissive -a -d sat,auto /dev/disk/by-uuid/$DUUID1 &>> $LOGF
#ELAPSED3=$(elapsed3)
#log "INFO" "SMART drive check complete on $MOUNT1 Elapsed: $ELAPSED3"

starttimer3
log "INFO" "Running NTFS Fix on $MOUNT1"
ntfsfix $DUUID1 &>> $LOGF 
ELAPSED3=$(elapsed3)
log "INFO" "NTFS Fix complete on $MOUNT1 Elapsed: $ELAPSED3"

if /bin/mount "$MOUNT1"; then
starttimer3
starttimer2
log "INFO" "Logs backup starting..."
/opt/galaxymediatools/backupscripts/backuplogs.exec
CRESULT=$(backupcomplete "Logs")

starttimer2
log "INFO" "Stand-Up Comedy Library backup starting..."
/opt/galaxymediatools/backupscripts/backupcomedy.exec 
CRESULT=$(backupcomplete "Stand-Up Comedy")

starttimer2
log "INFO" "Movie Library backup starting..."
/opt/galaxymediatools/backupscripts/backupmovies.exec
MRESULT=$(backupcomplete "Movie")

starttimer2
log "INFO" "Documentary Library backup starting..."
/opt/galaxymediatools/backupscripts/backupdocumentaries.exec
FRESULT=$(backupcomplete "Documentary")

starttimer2
log "INFO" "UFC Event Library backup starting..."
/opt/galaxymediatools/backupscripts/backupufc.exec
URESULT=$(backupcomplete "UFC Events")

starttimer2
log "INFO" "Short Film Library backup starting..."
/opt/galaxymediatools/backupscripts/backupshortfilms.exec
FRESULT=$(backupcomplete "Short Film")

starttimer2
log "INFO" "Music Library backup starting..."
/opt/galaxymediatools/backupscripts/backupmusic.exec
FRESULT=$(backupcomplete "Music")

starttimer2
log "INFO" "Pictures Library backup starting..."
/opt/galaxymediatools/backupscripts/backuppictures.exec
FRESULT=$(backupcomplete "Pictures")

starttimer2
log "INFO" "File Library backup starting..."
/opt/galaxymediatools/backupscripts/backupfiles.exec
FRESULT=$(backupcomplete "File")

starttimer2
log "INFO" "Other files backup starting..."
/opt/galaxymediatools/backupscripts/backupother.exec
FRESULT=$(backupcomplete "Other")

starttimer2
log "INFO" "Logs backup starting..."
/opt/galaxymediatools/backupscripts/backuplogs.exec
FRESULT=$(backupcomplete "Logs")

ELAPSED3=$(elapsed3)
log "INFO" "Backups on $MOUNT1 complete.  Elapsed: $ELAPSED3"

log "INFO" "Un-Mounting $MOUNT1"
/bin/sync
D1=`df -h | grep "$MOUNT1"`
IFS=' ' read -r -a D1INFO <<< $D1
D1PERC=${D1INFO[4]}
D1FREE=${D1INFO[3]}
/bin/umount $MOUNT1
else
 log "ERROR" "Backup Error, Backup1 not mounting!"
 pushover "backup" "Backup Error, Backup1 not mounting!"
fi

#starttimer3
#log "INFO" "SMART drive check starting on $MOUNT2"
#smartctl -T permissive -a -d sat,auto /dev/disk/by-uuid/$DUUID2 &>> $LOGF
#ELAPSED3=$(elapsed3)
#log "INFO" "SMART drive check complete on $MOUNT2 Elapsed: $ELAPSED3"

starttimer3
log "INFO" "Running NTFS Fix on $MOUNT2"
ntfsfix $DUUID2 &>> $LOGF
ELAPSED3=$(elapsed3)
log "INFO" "NTFS Fix complete on $MOUNT2 Elapsed: $ELAPSED3"

if /bin/mount "$MOUNT2"; then
starttimer3
starttimer2
log "INFO" "TV Show Library backup starting..."
/opt/galaxymediatools/backupscripts/backuptvshows.exec
TRESULT=$(backupcomplete "TV Show")

starttimer2
log "INFO" "Recorded TV Library backup starting..."
/opt/galaxymediatools/backupscripts/backuprecordedtv.exec
RRESULT=$(backupcomplete "Recorded TV")

ELAPSED3=$(elapsed3)
log "INFO" "Backups on $MOUNT2 complete.  Elapsed: $ELAPSED3"

log "INFO" "Un-Mounting $MOUNT2"
/bin/sync
D2=`df -h | grep "$MOUNT2"`
IFS=' ' read -r -a D2INFO <<< $D2
D2PERC=${D2INFO[4]}
D2FREE=${D2INFO[3]}
/bin/umount $MOUNT2
else
 log "ERROR" "Backup Error, Backup2 not mounting!"
 pushover "backup" "Backup Error, Backup2 not mounting!"
fi

log "INFO" "USB drive $MOUNT1 - $D1FREE Free, $D1PERC Used."
log "INFO" "USB drive $MOUNT2 - $D2FREE Free, $D2PERC Used."

ELAPSED=$(elapsed)
log "DEBUG" "CRESULT=$CRESULT, MRESULT=$MRESULT, URESULT=$URESULT, TRESULT=$TRESULT, RRESULT=$RRESULT"

if (( $CRESULT == 0 && $MRESULT == 0 && $URESULT == 0 && $TRESULT == 0 && $RRESULT == 0 )); then
log "INFO" "All Library backups completed successfully!"
pushover "backup" "Backups completed successfully! Backup1 $D1FREE Free, $D1PERC Used Backup2 $D2FREE Free, $D2PERC Used  Elapsed: $ELAPSED"
else
ERRORED=$(($CRESULT+$MRESULT+$URESULT+$TRESULT+$URESULT))
log "DEBUG" "ERRORED=$ERRORED"
log "INFO" "Backups completed with errors! $ERRORED Libraries failed. Elapsed: $ELAPSED"
pushover "backup" "Backups completed with errors! $ERRORED Libraries have failed!  Backup1 $D1FREE Free, $D1PERC Used Backup2 $D2FREE Free, $D2PERC Used Elapsed: $ELAPSED"
fi
log "INFO" "<--- Master Backup script completed. Elapsed: $ELAPSED"
