#!/bin/bash

LOGF="/video/Incoming/logs/backupmaster.log"
DUUID1="296A04BB7E0FD7B8"
DUUID2="01D2A5E1CE162C70"
MOUNT1=/mnt/backup1
MOUNT2=/mnt/backup2

starttimer
log "INFO" "---> Master Backup script starting"

if mountpoint -q $MOUNT1
then
umount $MOUNT1
fi

if mountpoint -q $MOUNT2
then
umount $MOUNT2
fi

ntfsfix /dev/disk/by-uuid/$DUUID1 >> $LOGF 

backupcomplete() {
ELAPSED2=$(elapsed2)
if [ $? -eq 0 ]; then
log "INFO" "$1 Library backup completed successfully. Elapsed: $ELAPSED2"
else
log "INFO" "$1 Library backup failed. Elapsed: $ELAPSED2"
fi
}

starttimer2
log "INFO" "Stand-Up Comedy Library backup starting..."
/opt/galaxymediatools/backupscripts/backupcomedy.exec 
backupcomplete "Stand-Up Comedy"

starttimer2
log "INFO" "Movie Library backup starting..."
/opt/galaxymediatools/backupscripts/backupmovies.exec
backupcomplete "Movie"

starttimer2
log "INFO" "UFC Event Library backup starting..."
/opt/galaxymediatools/backupscripts/backupufc.exec
backupcomplete "UFC Events"

ntfsfix /dev/disk/by-uuid/$DUUID2 >> $LOGF

starttimer2
log "INFO" "TV Show Library backup starting..."
/opt/galaxymediatools/backupscripts/backuptvshows.exec
backupcomplete "TV Show"

starttimer2
log "INFO" "Recorded TV Library backup starting..."
/opt/galaxymediatools/backupscripts/backuprecordedtv.exec
backupcomplete "Recorded TV"

if [ -f /var/run/reboot-required ]; then
  log "WARN" "Reboot required. Rebooting..."
  SUS=2
else
  log "INFO" "No Reboot needed. Suspending machine."
SUS=1
fi

ELAPSED=$(elapsed)
log "INFO" "<--- Master Backup script completed. Elapsed: $ELAPSED"

if [ $SUS -eq 1 ]; then
pm-suspend
else
reboot
fi
