#!/bin/bash

LOGF="/video/Incoming/logs/mediabackup/!backupmaster.txt"
DUUID="01D2A5E1CE162C70"
MOUNT=/mnt/backup2

if mountpoint -q $MOUNT
then
umount $MOUNT
fi

ntfsfix /dev/disk/by-uuid/$DUUID >> $LOGF

/opt/galaxymediatools/backupscripts/backuptvshows.exec
