directory: /music/process/sorted
library: /video/Other/beets/musiclibrary.dbi

pluginpath:
    /opt/whatlastgenre/plugin/beets/beetsplug

import:
    move: yes
    write: yes
    log: /video/Incoming/logs/beetsimporter.log

original_date: yes

threaded: yes
ui:
    color: yes

plugins: discogs beatport chroma acousticbrainz duplicates wlg convert badfiles info

duplicates:
    merge: yes

wlg:
    auto: no
    force: no
    count: 4
    separator: ', '
    whitelist: wlg

paths:
    default: %left{$albumartist_sort,1}/$albumartist_sort/$album%if{$original_year, ($original_year),%if{$year, ($year)}}/$track - $albumartist - $title
    singleton: %left{$artist_sort,1}/$artist_sort/$artist - $title%if{$year, ($year)}
    comp: Compilations/$genre/$album%if{$year, ($year)}/$track - $artist - $title
    albumtype:soundtrack: Soundtracks/$album%if{$year, ($year)}/$track - $artist - $title
