directory: /music/process/sorted
library: /video/Other/beets/musiclibrary.dbi

pluginpath:
    /opt/whatlastgenre/plugin/beets/beetsplug

wlg:
    auto: yes
    force: yes
    count: 4
    separator: ', '
    whitelist: wlg

import:
    move: yes
    write: yes
    log: /video/Incoming/logs/beetsimporter.log

threaded: yes
ui:
    color: no

plugins: discogs beatport chroma acousticbrainz duplicates convert badfiles info wlg

duplicates:
    merge: yes

paths:
    default: %left{$albumartist_sort,1}/$albumartist_sort/$album%if{$year, ($year)}/$track - $albumartist - $title
    singleton: %left{$artist_sort,1}/$artist_sort/$artist - $title%if{$year, ($year)}
    comp: Compilations/$genre/$album%if{$year, ($year)}/$track - $artist - $title
    albumtype:soundtrack: Soundtracks/$album%if{$year, ($year)}/$track - $artist - $title
