directory: /music/process/sorted
library: /video/Other/beets/musiclibrary.dbi

pluginpath:
    /opt/whatlastgenre/plugin/beets/beetsplug

import:
    move: yes
    write: yes
    log: /video/Incoming/logs/beetsimporter.log

original_date: yes

threaded: yes
ui:
    color: yes

plugins: discogs beatport chroma acousticbrainz duplicates convert fromfilename ftintitle importadded badfiles lastgenre scrub info

duplicates:
    merge: yes
    
tiebreak: 
    items: [bitrate]

wlg:
    auto: no
    force: no
    count: 1
    separator: ', '
    whitelist: wlg

paths:
    default: %upper{%left{$albumartist_sort,1}}/%title{$albumartist_sort}/%title{$album}%if{$original_year, ($original_year),%if{$year, ($year)}}/$track - %title{$albumartist} - %title{$title}
    singleton: %upper{%left{$artist_sort,1}}/%title{$artist_sort}/%title{$artist} - %title{$title}%if{$year, ($year)}
    comp: Compilations/$genre/%title{$album}%if{$year, ($year)}/$track - %title{$artist} - %title{$title}
    albumtype:soundtrack: Compilations/Soundtracks/%title{$album}%if{$year, ($year)}/$track - %title{$artist} - %title{$title}
