directory: /mnt/storage/music
library: /video/Other/beets/musiclibrary.dbi

pluginpath:
    /opt/whatlastgenre/plugin/beets/beetsplug

import:
    move: yes
    write: yes
    log: /mnt/storage/video/Incoming/logs/beetsimporter.log

original_date: yes

threaded: yes
ui:
    color: yes

plugins: discogs beatport chroma acousticbrainz duplicates convert fromfilename rewrite ftintitle importadded badfiles lastgenre scrub info

duplicate_action: ask

match:
    strong_rec_thresh: 0.04

duplicates:
    merge: yes
    
tiebreak: 
    items: [bitrate]

lastgenre:
    count: 4
    force: yes
    source: track
    separator: ', '
    whitelist: yes

wlg:
    auto: no
    force: no
    count: 4
    separator: ', '
    whitelist: wlg

rewrite:
    artist The Jimi Hendrix Experience: Jimi Hendrix
    artist Sonny Moore: Skrillex
    artist Lorin Ashton: Bassnectar
    artist Bsod: Deadmau5
    artist Makaveli: 2Pac
    artist Stevie Ray Vaughan and Double Trouble: Stevie Ray Vaughan
    artist Prince \& The New Power Generation: Prince
    artist Prince and The Revolution: Prince
    artist Marilyn Manson and the Spooky Kids: Marilyn Manson
    artist John Coltrane Quartet: John Coltrane
    artist Satan on Fire: Marilyn Manson
    artist John Scofield Band: John Scofield
    artist Infiniti: Juan Atkins

paths:
    default: %upper{%left{$albumartist_sort,1}}/%title{$albumartist_sort}/%title{$album}%if{$original_year, ($original_year),%if{$year, ($year)}}/$track - %title{$albumartist} - %title{$title}
    singleton: %upper{%left{$artist_sort,1}}/%title{$artist_sort}/%title{$artist} - %title{$title}%if{$year, ($year)}
    comp: Compilations/$genre/%title{$album}%if{$year, ($year)}/$track - %title{$artist} - %title{$title}
    albumtype:soundtrack: Compilations/Soundtracks/%title{$album}%if{$year, ($year)}/$track - %title{$artist} - %title{$title}
